# -*- coding: utf-8 -*-
"""Scientific_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCGAfEBlG4vq9ITaStsQj763KaW6YG_A

# Phase 0: Pipeline Initialization, Data Sourcing & Architectural Setup

### 🎯 Overview & Action Plan
Before executing any analytical or computational task, establishing a rigid, warning-free environment and securing data alignment is paramount. This initial phase sets up our scientific computing ecosystem.

Our architectural plan for this phase consists of:
1. **Workspace Anchoring:** Mounting the remote Google Drive repository to ensure persistent data streams.
2. **Environment Stabilization:** Silencing core runtime warnings (`FutureWarning` / `UserWarning`) to guarantee clean, professional reporting.
3. **Multi-Algorithmic Dependency Loading:** Importing specialized modules for mathematical computing (`numpy`, `pandas`), scientific visualization (`seaborn`, `matplotlib`), and latent space decomposition (`sklearn`).
4. **Feature Space Harmonization:** Segregating the clinical ground-truth target from the independent variable matrices.
"""

# =======================================================================
#    HEART DISEASE PROJECT - PHASE 0: SETUP & INITIALIZATION
# =======================================================================

# --- 0.1 REMOTE WORKSPACE MOUNTING ---
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# --- 0.2 ENVIRONMENT STABILIZATION ---
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=UserWarning)

# --- 0.3 MATHEMATICAL, GRAPHICAL & ML DEPENDENCIES ---
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from scipy.cluster.hierarchy import linkage, dendrogram
import statsmodels.api as sm

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances
from sklearn.ensemble import RandomForestClassifier

sns.set_theme(style="whitegrid")

# --- 0.4 DATA SOURCING ---
path = '/content/drive/MyDrive/heart.csv'
df = pd.read_csv(path)

# --- 0.5 DATASET AUDIT ---
print("======================================================================")
print("🔬 WORKSPACE RUNTIME METRIC AUDIT")
print("======================================================================")
print(f"📐 Raw Clinical DataFrame Shape : {df.shape}")
print(f"📋 Dataset Columns              : {df.columns.tolist()}")
print("======================================================================")

"""# Phase 1: Data Quality Audit & Exploratory Expression Profiling

### 🎯 Objective
Before injecting data into dimensionality reduction algorithms, a rigorous quality audit is mandatory. This phase ensures data integrity, checks for missing attributes that could compromise matrix operations, and examines the initial global correlation architecture of our clinical features.

Our pipeline implements:
1. **Matrix Completeness Check:** Explicit verification of null entry vectors.
2. **Global Correlation Profiling:** Mapping the unmodified feature space to identify initial collinearity patterns before geometric standard scaling.
"""

# =======================================================================
#    HEART DISEASE PROJECT - PHASE 1: DATA AUDIT & CORRELATION PROFILING
# =======================================================================

# --- 1 MATRIX COMPLETENESS & INTEGRITY AUDIT ---
print("======================================================================")
print("🔬 INITIAL DATASET COMPLETENESS AUDIT")
print("======================================================================")
print(f"📐 Dataset Matrix Dimensions (Samples x Features): {df.shape}")

missing_values = df.isnull().sum()
if missing_values.sum() == 0:
    print("✅ Matrix Integrity: 100% complete. Zero missing entries detected.")
else:
    print("⚠️ Missing values detected within the following vectors:")
    print(missing_values[missing_values > 0])
print("======================================================================")

# --- 1.2 GLOBAL FEATURE CORRELATION ARCHITECTURE ---
# Computing the Pearson product-moment correlation coefficients
corr_matrix = df.corr()

# Generating a strict upper triangle mask to eliminate geometric redundancy
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))

# Setting up the professional plotting canvas
fig, ax = plt.subplots(figsize=(12, 10))

# Customizing the heatmap using a diverging, scientifically sound colormap (RdBu_r)
sns.heatmap(
    corr_matrix,
    mask=mask,
    annot=True,
    fmt=".2f",
    cmap="RdBu_r",
    center=0,
    square=True,
    linewidths=0.5,
    cbar_kws={"shrink": .75, "label": "Pearson Correlation Coefficient ($r$)"},
    annot_kws={"size": 8, "fontweight": "medium"},
    ax=ax
)

# Refined title and layout adjustments (preventing label truncation)
ax.set_title("Initial Feature Space Correlation Matrix (Lower Triangle)", fontsize=13, fontweight='bold', pad=18)
plt.tight_layout()
plt.show()

"""### 🔍 Duplicate Record Audit

Before proceeding with downstream analyses, we verify whether the dataset contains repeated observations. Duplicate rows may artificially increase the weight of specific patient profiles, distort descriptive statistics, and bias both clustering and supervised models. This audit reports the total number of records, the number of exact duplicates, and the effective number of unique patient profiles.

"""

# =======================================================================
# PHASE 1.1: DUPLICATE RECORD AUDIT
# =======================================================================

duplicate_count = df.duplicated().sum()
unique_count = len(df.drop_duplicates())

print("=" * 65)
print("DUPLICATE RECORD AUDIT")
print("=" * 65)
print(f"Total rows:      {len(df)}")
print(f"Duplicate rows:  {duplicate_count}")
print(f"Unique patients: {unique_count}")
print("=" * 65)

"""### 🧹 Duplicate Removal and Dataset Consolidation

After identifying repeated observations, exact duplicates are removed to preserve one instance of each patient profile. The index is then reset to maintain a clean and continuous data structure. A final verification confirms the resulting dataset dimensions and ensures that no duplicate rows remain before preprocessing and modelling.

"""

# =======================================================================
# PHASE 1.2: DUPLICATE REMOVAL
# =======================================================================

df = df.drop_duplicates().reset_index(drop=True)

print("=" * 65)
print("DATASET AFTER DUPLICATE REMOVAL")
print("=" * 65)
print(f"Final dataset shape: {df.shape}")
print(f"Remaining duplicate rows: {df.duplicated().sum()}")
print("=" * 65)

"""# Phase 2: FULL CROSS-CORRELATION MATRIX

### 🔍 Full-Scale Cross-Correlation Mapping

To evaluate the complete interplay across the entire continuous and discrete feature space, we compute an unmasked, full-scale Pearson cross-correlation profile. While a masked lower-triangle representation isolates directional dependencies, mapping the symmetrical structure provides an extensive global layout of the dataset. This architectural view allows for a quick diagnostic of potential collinear variables that could impact our linear decompositions.
"""

# =======================================================================
# PHASE 2: FULL CROSS-CORRELATION MATRIX
# =======================================================================

# 2.1 COMPUTING SYMMETRIC PRODUCT-MOMENT COEFFICIENTS
# Calculating Pearson matrices to observe raw directional association weights
corr = df.corr()

# 2.2 CANVAS PARAMETRIZATION & HEATMAP GENERATION
plt.figure(figsize=(12, 10))

# Applying the high-contrast diverging colormap (RdBu_r) centered perfectly at zero
sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap='RdBu_r',
    center=0,
    square=True,
    linewidths=.5,
    cbar_kws={"shrink": .8, "label": "Pearson Correlation Coefficient ($r$)"},
    annot_kws={"size": 9, "fontweight": "medium"}
)

# 2.3 REFINING FORMATTING AND ROTATION STATES
plt.title("Scientific Visualization: Full Symmetrical Feature Correlation Network", fontsize=13, fontweight='bold', pad=20)
plt.xticks(fontsize=10, rotation=45, ha='right')
plt.yticks(fontsize=10)
plt.tight_layout()
plt.show()

"""## 🔍 Distributional Audit & Outlier Screening

Before applying coordinate transformations or space alignment workflows, evaluating the distributional properties and presence of extreme values in continuous features is an essential preliminary step. As part of our exploratory data analysis and data cleaning pipeline, this framework utilizes a dual-panel boxplot to screen key continuous parameters—specifically serum cholesterol (`chol`) and resting blood pressure (`trestbps`)—stratified across clinical cohorts (Healthy vs. Diseased).

While observing individual biomarkers is useful for initial univariate screening (highlighting potential outliers, skewness, and the necessity for robust standard scaling before distance-based models), it represents only a local view of the data. This visualization confirms both the presence of extreme values and the limitations of isolated features, reinforcing the methodological necessity to transition toward global, multivariate representations and dimensionality reduction techniques.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Creating a figure with the most relevant clinical parameters split by disease presence/absence
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Boxplot for Cholesterol (X-axis = Health status / Target)
sns.boxplot(
    x="target",
    y="chol",
    data=df,
    ax=axes[0],
    palette=["#2ecc71", "#e74c3c"],
    width=0.4,
)
axes[0].set_title(
    "Serum Cholesterol Distribution (chol) by Clinical Status", fontsize=12
)
axes[0].set_xlabel("Heart Disease Status (0 = Absent, 1 = Present)")
axes[0].set_ylabel("Serum Cholesterol (mg/dL)")

# Boxplot for Resting Blood Pressure (X-axis = Health status / Target)
sns.boxplot(
    x="target",
    y="trestbps",
    data=df,
    ax=axes[1],
    palette=["#2ecc71", "#e74c3c"],
    width=0.4,
)
axes[1].set_title("Resting Blood Pressure Distribution (trestbps)", fontsize=12)
axes[1].set_xlabel("Heart Disease Status (0 = Absent, 1 = Present)")
axes[1].set_ylabel("Blood Pressure (mmHg)")

plt.tight_layout()
plt.show()

"""# Phase 3: Data Preprocessing, Feature Scaling & Geometric Alignment

### 🎯 Objective
Parametric mathematical decompositions (such as PCA) and centroid-based distance algorithms require variables to be on a uniform geometric scale. This section separates the independent clinical metrics from the ground-truth diagnosis labels and applies a standard Z-score transformation. This forces each parameter to possess a mean of 0 and a standard deviation of 1, ensuring isotropic variance across the entire space.
"""

# =======================================================================
#    HEART DISEASE PROJECT - PHASE 3: FEATURE SCALING & SYSTEM VERIFICATION
# =======================================================================

# 3.1 MATRIX ISOLATION
# Separating independent clinical variables from the categorical target label
X = df.drop("target", axis=1)
y = df["target"]

# 3.2 GEOMETRIC STANDARD SCALING (Z-SCORE)
# Transforming features to center their distribution and balance mathematical weights
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 3.3 METRIC INTEGRITY VERIFICATION
print("======================================================================")
print("🔬 PREPROCESSING OPERATIONAL METRIC VERIFICATION")
print("======================================================================")
print(f"📐 Processed Predictor Matrix Dimensions : {X_scaled.shape}")
print(
    f"µ Empirical Scaled Vector Mean        : {np.round(X_scaled.mean(), 2)} (Expected: ~0)"
)
print(
    f"σ Empirical Scaled Vector Std Dev     : {X_scaled.std()} (Expected: 1)"
)
print("======================================================================")
print("\nFirst 2 standardized rows matrix sample:")
print(np.round(X_scaled[:2], 3))
print("======================================================================")

"""# Phase 4: Exploratory Data Analysis & Primary Correlation Insights

### 🎯 Objective
Following the global linear space decomposition, we return to the raw clinical feature space to run an targeted, explicit correlation audit against our diagnostic endpoint (`target`). This step isolates and identifies the precise physiological features that share the highest linear variance with the presence or absence of cardiac disease, establishing our first direct clinical insights.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Select continuous variables from the dataset
continuous_columns = ["age", "trestbps", "chol", "thalach", "oldpeak"]
df_continuous = df[continuous_columns]

# Compute the complete Pearson correlation matrix
corr_matrix = df_continuous.corr()

# Canvas and Complete Heatmap (Without empty cuts, clean and readable)
plt.figure(figsize=(9, 7))

sns.heatmap(
    corr_matrix,
    annot=True,
    fmt=".2f",
    cmap="RdBu_r",
    center=0,
    square=True,
    linewidths=0.8,
    cbar_kws={
        "shrink": 0.8,
        "label": "Pearson Correlation Coefficient ($r$)",
    },
    annot_kws={"size": 10, "weight": "bold"},
)

plt.title(
    "Complete Correlation Matrix Among Continuous Clinical Features",
    fontsize=13,
    fontweight="bold",
    pad=15,
)
plt.xticks(fontsize=10, rotation=45, ha="right")
plt.yticks(fontsize=10)

plt.tight_layout()
plt.show()

"""# Phase 5: Latent Space Geometry & Dimensionality Reduction (PCA Biplot)

### 🎯 Objective
To compress the high-dimensional standardized feature space into an optimized 2D plane, we execute Principal Component Analysis (PCA). This linear mathematical decomposition allows us to project the multi-omic and clinical feature vectors alongside patient coordinates onto the primary orthogonal eigenvectors ($PC1$ and $PC2$). This step is critical to visualize data variance and determine how specific biomarkers dynamically drive patient classification.

### 📊 PCA Explained-Variance Profile

Before interpreting a two-dimensional PCA projection, it is necessary to quantify how much information is retained by each principal component. The scree plot displays the percentage of variance explained individually by every component, while the cumulative curve shows how progressively adding components reconstructs the original feature space. The 80% reference line provides an intuitive benchmark for assessing the dimensionality required to preserve most of the dataset variability.
"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Select ONLY continuous variables
continuous_columns = ["age", "trestbps", "chol", "thalach", "oldpeak"]
X = df[continuous_columns]

# Mandatory standardization (Z-score)
X_scaled = StandardScaler().fit_transform(X)

# PCA computation
pca = PCA().fit(X_scaled)
exp_var = pca.explained_variance_ratio_ * 100
cum_var = np.cumsum(exp_var)

# Optimized plot (Tufte Style / Whitegrid)
sns.set_theme(style="whitegrid")
fig, ax1 = plt.subplots(figsize=(9, 5))

# Bars for Single Variance
n_components = len(continuous_columns)
x_ticks = np.arange(1, n_components + 1)

bars = ax1.bar(
    x_ticks,
    exp_var,
    color="#8da0cb",
    alpha=0.85,
    width=0.6,
    label="Explained Variance (%)",
)
ax1.set_xlabel("Principal Component (PC)", fontsize=11, fontweight="bold")
ax1.set_ylabel("Single Explained Variance (%)", fontsize=11, color="#386cb0")
ax1.set_xticks(x_ticks)
ax1.set_ylim(0, max(exp_var) + 10)
ax1.grid(False)  # Removes unnecessary vertical grid (Decluttering)

# Line for Cumulative Variance
ax2 = ax1.twinx()
line = ax2.plot(
    x_ticks,
    cum_var,
    color="#d95f02",
    marker="o",
    linewidth=2,
    label="Cumulative Variance (%)",
)
ax2.set_ylabel("Cumulative Explained Variance (%)", fontsize=11, color="#d95f02")
ax2.set_ylim(0, 105)
ax2.grid(True, linestyle=":", alpha=0.5)

# 80% Threshold (Highlighting)
ax2.axhline(80, color="gray", linestyle="--", alpha=0.7, label="80% Threshold")

plt.title(
    "PCA: Scree Plot of Variance (Standardized Continuous Features)",
    fontsize=13,
    pad=15,
    fontweight="bold",
)
fig.tight_layout()
plt.show()

"""### 🧭 PCA Biplot: Patients and Feature Loadings

The biplot combines two complementary layers of information in the same latent space. Patient observations are projected onto the first two principal components and colored according to their true clinical status, while arrows represent feature loadings. The direction and length of each arrow indicate how strongly and in which direction the original clinical variables contribute to the principal components, helping connect the geometric patient distribution with its physiological drivers.

"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Select ONLY continuous variables for PCA
continuous_columns = ["age", "trestbps", "chol", "thalach", "oldpeak"]
X = df[continuous_columns]
y = df["target"]  # Used ONLY to color the points

# Z-score standardization
X_scaled = StandardScaler().fit_transform(X)

# 2-component PCA calculation
pca = PCA(n_components=2)
components = pca.fit_transform(X_scaled)
loadings = pca.components_  # Feature vectors

# DataFrame for projection
df_pca = pd.DataFrame(components, columns=["PC1", "PC2"])
df_pca["Diagnosis"] = y.map({0: "Healthy (0)", 1: "Pathological (1)"})

# Plotting (Tufte Style / Decluttered)
sns.set_theme(style="whitegrid")
plt.figure(figsize=(9, 7))

# Scatterplot of patients with distinct and transparent colors
sns.scatterplot(
    data=df_pca,
    x="PC1",
    y="PC2",
    hue="Diagnosis",
    palette=["#2b83ba", "#d7191c"],
    alpha=0.6,
    s=50,
)

# Add arrows ONLY for continuous variables
scale_factor = 3.5  # Scale the arrows to make them clearly visible over the points
for i, feature in enumerate(continuous_columns):
    x_val = loadings[0, i] * scale_factor
    y_val = loadings[1, i] * scale_factor

    # Draw the arrow with dark and sharp color (black/dark gray)
    plt.arrow(
        0,
        0,
        x_val,
        y_val,
        color="#2b2b2b",
        alpha=0.9,
        linewidth=1.5,
        head_width=0.1,
    )

    # Smart offset to prevent text overlap
    offset_x = 1.15 if x_val >= 0 else 1.25
    offset_y = 1.15 if y_val >= 0 else 1.25
    plt.text(
        x_val * offset_x,
        y_val * offset_y,
        feature,
        color="#000000",
        ha="center",
        va="center",
        fontweight="bold",
        fontsize=10,
        bbox=dict(
            boxstyle="round,pad=0.2", facecolor="white", alpha=0.8, edgecolor="none"
        ),
    )

# Origin axes (0,0)
plt.axhline(0, color="gray", linestyle="--", linewidth=0.8)
plt.axvline(0, color="gray", linestyle="--", linewidth=0.8)

# Clear titles and labels with explained %
var_pc1 = pca.explained_variance_ratio_[0] * 100
var_pc2 = pca.explained_variance_ratio_[1] * 100

plt.title("PCA Biplot: Projection and Loadings of Continuous Features", fontsize=13, fontweight="bold", pad=15)
plt.xlabel(f"PC1 ({var_pc1:.1f}% Explained Variance)", fontsize=11)
plt.ylabel(f"PC2 ({var_pc2:.1f}% Explained Variance)", fontsize=11)
plt.legend(title="Clinical Status", loc="upper right")

plt.tight_layout()
plt.show()

"""# Phase 6: Latent Space Geometry & 2D Cohort Projections

### 🎯 Objective
Following the generation of our Biplot, we map an isolated 2D projection of the patient cohort onto the first two Principal Components ($PC1$ and $PC2$). By stripping away the loading vectors, this visualization focuses entirely on evaluating the geometric density, clustering, and spatial distributions of the samples based on their true underlying clinical status (Ground Truth).
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib.patches import Ellipse
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# 1. Select ONLY continuous variables
continuous_columns = ["age", "trestbps", "chol", "thalach", "oldpeak"]
X = df[continuous_columns]
y = df["target"]

# 2. Z-Score Standardization
X_scaled = StandardScaler().fit_transform(X)

# 3. 2D PCA Calculation
pca = PCA(n_components=2)
components = pca.fit_transform(X_scaled)
var_pc1, var_pc2 = pca.explained_variance_ratio_ * 100

df_pca = pd.DataFrame(components, columns=["PC1", "PC2"])
df_pca["Diagnosis"] = y.map({0: "Healthy (0)", 1: "Pathological (1)"})

# 4. Plotting
sns.set_theme(style="whitegrid")
plt.figure(figsize=(9, 6))

# Colorblind-Safe Palette: Blue (Healthy) vs Red/Orange (Pathological)
palette_safe = {"Healthy (0)": "#2b83ba", "Pathological (1)": "#d7191c"}

# Scatterplot with transparency to reduce overplotting
ax = sns.scatterplot(
    data=df_pca,
    x="PC1",
    y="PC2",
    hue="Diagnosis",
    palette=palette_safe,
    alpha=0.6,
    s=60,
    edgecolor="none",
)


# Function to draw the Confidence Ellipse (Gestalt Principle / Enclosure)
def draw_confidence_ellipse(data, ax, color, label):
    x = data["PC1"]
    y = data["PC2"]
    cov = np.cov(x, y)
    lambda_, v = np.linalg.eig(cov)
    lambda_ = np.sqrt(lambda_)

    # Ellipse at 2 Standard Deviations (approx. 95% confidence)
    ellipse = Ellipse(
        xy=(np.mean(x), np.mean(y)),
        width=lambda_[0] * 2 * 2,
        height=lambda_[1] * 2 * 2,
        angle=np.rad2deg(np.arctan2(*v[:, 0][::-1])),
        facecolor=color,
        alpha=0.15,
        edgecolor=color,
        linewidth=2,
        linestyle="--",
    )
    ax.add_patch(ellipse)


# Draw ellipses for both groups
draw_confidence_ellipse(
    df_pca[df_pca["Diagnosis"] == "Healthy (0)"], ax, "#2b83ba", "Healthy"
)
draw_confidence_ellipse(
    df_pca[df_pca["Diagnosis"] == "Pathological (1)"], ax, "#d7191c", "Pathological"
)

# Labels and Titles
plt.title(
    "PCA Projection of Patients (Standardized Continuous Features)",
    fontsize=13,
    fontweight="bold",
    pad=15,
)
plt.xlabel(
    f"PC1 ({var_pc1:.1f}% Explained Variance)", fontsize=11, fontweight="bold"
)
plt.ylabel(
    f"PC2 ({var_pc2:.1f}% Explained Variance)", fontsize=11, fontweight="bold"
)
plt.legend(title="Clinical Status", loc="upper right")

plt.tight_layout()
plt.show()

"""### 🔢 Data-Driven Selection of the Number of Clusters

Before fixing the number of K-Means clusters, we compare candidate solutions from \(K=2\) to \(K=8\). The Elbow Method evaluates the reduction in within-cluster inertia as additional clusters are introduced, whereas the Silhouette Score measures cohesion within clusters and separation between them. Considering both criteria reduces the risk of selecting \(K\) arbitrarily and provides quantitative support for the final clustering configuration.

"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

# 1. Select continuous variables and apply Z-Score
continuous_columns = ["age", "trestbps", "chol", "thalach", "oldpeak"]
X_scaled = StandardScaler().fit_transform(df[continuous_columns])

# 2. Compute Inertia and Silhouette for K from 2 to 8
k_range = range(2, 9)
inertias = []
silhouettes = []

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10).fit(X_scaled)
    inertias.append(kmeans.inertia_)
    silhouettes.append(silhouette_score(X_scaled, kmeans.labels_))

# 3. Creation of the Combined Plot (Tufte Style / Whitegrid)
sns.set_theme(style="whitegrid")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.5))

# --- PLOT 1: ELBOW METHOD ---
ax1.plot(k_range, inertias, color="#2b83ba", marker="o", linewidth=2, ms=6)
# Highlighting K=2 or K=3 (e.g., K=2)
opt_k = 2
ax1.plot(
    opt_k,
    inertias[k_range.index(opt_k)],
    marker="o",
    ms=10,
    color="#d7191c",
    label=f"Optimal K ({opt_k})",
)

ax1.set_title("Elbow Method (Inertia)", fontsize=12, fontweight="bold")
ax1.set_xlabel("Number of Clusters (K)", fontsize=11)
ax1.set_ylabel("Within-Cluster Inertia", fontsize=11)
ax1.set_xticks(k_range)
ax1.grid(True, linestyle=":", alpha=0.5)

# --- PLOT 2: SILHOUETTE ANALYSIS ---
ax2.plot(k_range, silhouettes, color="#2b83ba", marker="o", linewidth=2, ms=6)
# Highlighting the Silhouette peak
max_sil_idx = np.argmax(silhouettes)
best_k = k_range[max_sil_idx]
ax2.plot(
    best_k,
    silhouettes[max_sil_idx],
    marker="o",
    ms=10,
    color="#d7191c",
    label=f"Silhouette Peak (K={best_k})",
)

ax2.set_title("Silhouette Analysis", fontsize=12, fontweight="bold")
ax2.set_xlabel("Number of Clusters (K)", fontsize=11)
ax2.set_ylabel("Average Silhouette Score", fontsize=11)
ax2.set_xticks(k_range)
ax2.grid(True, linestyle=":", alpha=0.5)
ax2.legend(loc="upper right")

plt.suptitle(
    "Data-Driven Guided Selection of the Optimal Number of Clusters (K)",
    fontsize=14,
    fontweight="bold",
    y=1.03,
)
plt.tight_layout()
plt.show()

"""# Phase 7: Unsupervised Partitioning & Latent Space Boundary Auditing (K-Means Evaluation)

### 🎯 Objective
In this section, we transition to unsupervised partitioning to evaluate whether the continuous and discrete features group patients logically without relying on clinical diagnosis classes. By training a $K$-Means algorithm ($K=2$) directly on the standardized isotropic matrix, we can draw a direct mathematical comparison against the true diagnostic status and measure cluster separation boundaries through silhouette scoring metrics.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib.patches import Ellipse
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix, silhouette_score
from sklearn.preprocessing import StandardScaler

# Continuous Data Preparation & Z-Score
continuous_columns = ["age", "trestbps", "chol", "thalach", "oldpeak"]
X_scaled = StandardScaler().fit_transform(df[continuous_columns])
y_true = df["target"]  # 0=Healthy, 1=Diseased

# PCA and K-Means Clustering (K=2)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
var_pc1, var_pc2 = pca.explained_variance_ratio_ * 100

kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
cluster_labels = kmeans.fit_predict(X_scaled)

# DataFrame for Visualization
df_res = pd.DataFrame(X_pca, columns=["PC1", "PC2"])
df_res["Ground_Truth"] = y_true.map({0: "Healthy (0)", 1: "Pathological (1)"})
# Map clusters to align them chromatically with Ground Truth
df_res["Cluster"] = pd.Series(cluster_labels).map(
    {0: "Cluster 1 (Healthy)", 1: "Cluster 2 (Pathological)"}
)

# PLOTTING - 3-Section Panel (2 Scatters + 1 Contingency Heatmap)
sns.set_theme(style="whitegrid")
fig = plt.figure(figsize=(14, 5))
gs = fig.add_gridspec(1, 3, width_ratios=[1, 1, 0.6])

ax1 = fig.add_subplot(gs[0])
ax2 = fig.add_subplot(gs[1])
ax3 = fig.add_subplot(gs[2])

# Unique and accessible palette (Colorblind-Safe)
colors = {"Healthy (0)": "#2b83ba", "Pathological (1)": "#d7191c"}
cluster_colors = {
    "Cluster 1 (Healthy)": "#2b83ba",
    "Cluster 2 (Pathological)": "#d7191c",
}


# Function to draw Confidence Ellipse
def add_ellipse(data, x_col, y_col, ax, color):
    x, y = data[x_col], data[y_col]
    cov = np.cov(x, y)
    lambda_, v = np.linalg.eig(cov)
    lambda_ = np.sqrt(lambda_)
    ellipse = Ellipse(
        xy=(np.mean(x), np.mean(y)),
        width=lambda_[0] * 2 * 2,
        height=lambda_[1] * 2 * 2,
        angle=np.rad2deg(np.arctan2(*v[:, 0][::-1])),
        facecolor=color,
        alpha=0.15,
        edgecolor=color,
        linewidth=1.5,
        linestyle="--",
    )
    ax.add_patch(ellipse)

# PLOT 1: GROUND TRUTH
sns.scatterplot(
    data=df_res,
    x="PC1",
    y="PC2",
    hue="Ground_Truth",
    palette=colors,
    alpha=0.6,
    ax=ax1,
    s=40,
)
add_ellipse(
    df_res[df_res["Ground_Truth"] == "Healthy (0)"], "PC1", "PC2", ax1, "#2b83ba"
)
add_ellipse(
    df_res[df_res["Ground_Truth"] == "Pathological (1)"],
    "PC1",
    "PC2",
    ax1,
    "#d7191c",
)
ax1.set_title("True Clinical Status (Ground Truth)", fontweight="bold")
ax1.set_xlabel(f"PC1 ({var_pc1:.1f}%)")
ax1.set_ylabel(f"PC2 ({var_pc2:.1f}%)")

# PLOT 2: UNSUPERVISED CLUSTERS
sns.scatterplot(
    data=df_res,
    x="PC1",
    y="PC2",
    hue="Cluster",
    palette=cluster_colors,
    alpha=0.6,
    ax=ax2,
    s=40,
)
ax2.set_title("Assigned Clusters (K-Means)", fontweight="bold")
ax2.set_xlabel(f"PC1 ({var_pc1:.1f}%)")
ax2.set_ylabel("")

# PLOT 3: CONTINGENCY HEATMAP (Instead of black terminal table)
cm = confusion_matrix(y_true, cluster_labels)
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    cbar=False,
    ax=ax3,
    xticklabels=["Cluster 1", "Cluster 2"],
    yticklabels=["Healthy (0)", "Pathological (1)"],
    annot_kws={"size": 12, "weight": "bold"},
)
ax3.set_title("Contingency Matrix", fontweight="bold")
ax3.set_ylabel("True Diagnosis")
ax3.set_xlabel("K-Means Cluster")

plt.suptitle(
    "Structural Comparison: True Diagnosis vs. Unsupervised Clustering",
    fontsize=13,
    fontweight="bold",
    y=1.03,
)
plt.tight_layout()
plt.show()

"""### ✅ Agreement Between Unsupervised Clusters and Clinical Diagnosis

Because K-Means is trained without access to the target label, its cluster identifiers cannot be compared directly through simple label matching. We therefore use the Adjusted Rand Index (ARI) and Normalized Mutual Information (NMI), two label-invariant metrics that quantify the structural agreement between the discovered partition and the true diagnostic classes. Higher values indicate that the unsupervised organization captures clinically meaningful information.

"""

# =======================================================================
# PHASE 7.1: CLUSTER-TO-TARGET AGREEMENT
# =======================================================================

from sklearn.metrics import (
    adjusted_rand_score,
    normalized_mutual_info_score
)

ari = adjusted_rand_score(y_true, cluster_labels)
nmi = normalized_mutual_info_score(y_true, cluster_labels)

print("=" * 60)
print("CLUSTER AGREEMENT WITH CLINICAL DIAGNOSIS")
print("=" * 60)
print(f"Adjusted Rand Index:          {ari:.3f}")
print(f"Normalized Mutual Information: {nmi:.3f}")
print("=" * 60)

"""### 🌳 Hierarchical Clustering and Dendrogram Validation

To verify whether the cluster structure is specific to K-Means or also emerges under a different unsupervised method, we apply agglomerative hierarchical clustering with Ward linkage. The dendrogram represents the progressive merging of patient groups according to their multivariate similarity. A horizontal cut corresponding to two clusters allows a visual assessment of the separation level and provides an independent validation of the \(K=2\) solution.

"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy.cluster.hierarchy import (
    dendrogram,
    linkage,
    set_link_color_palette,
)
from sklearn.preprocessing import StandardScaler

# Select ONLY continuous variables and apply Z-Score
continuous_columns = ["age", "trestbps", "chol", "thalach", "oldpeak"]
X_scaled = StandardScaler().fit_transform(df[continuous_columns])

# Hierarchical Linkage Calculation (Ward Method)
Z = linkage(X_scaled, method="ward")

# Set the cut threshold (Threshold for K=2)
cut_distance = (Z[-1, 2] + Z[-2, 2]) / 2

# Set hierarchy colors (Consistent with the global palette)
set_link_color_palette(["#2b83ba", "#d7191c"])  # Blue (Cluster 1), Red (Cluster 2)

# PLOTTING (Style White / Tufte)
sns.set_theme(style="white")
plt.figure(figsize=(10, 5))

dendrogram(
    Z,
    truncate_mode="lastp",  # Clean truncation of leaves
    p=16,  # Show 16 macro-leaves
    leaf_rotation=0,
    leaf_font_size=10,
    show_contracted=True,
    color_threshold=cut_distance,  # Colors change EXACTLY at the threshold
    above_threshold_color="#555555",  # Upper branch in dark gray
)

# Cut line for K=2
plt.axhline(
    y=cut_distance,
    color="#d7191c",
    linestyle="--",
    linewidth=1.8,
    label=f"Cut Threshold K=2 (Dist={cut_distance:.1f})",
)

# Titles and Labels
plt.title(
    "Hierarchical Dendrogram of Clinical Profiles (Ward Method)",
    fontsize=13,
    fontweight="bold",
    pad=15,
)
plt.xlabel("Patient Groups (Sample Size)", fontsize=11, labelpad=10)
plt.ylabel("Linkage Distance (Ward Method)", fontsize=11)
plt.legend(loc="upper right")

# Decluttering: Remove unnecessary borders
sns.despine()

plt.tight_layout()
plt.show()

# Restore default Scipy palette (Best practice)
set_link_color_palette(None)

"""### 🧬 Feature Drivers of the Unsupervised Clusters

After defining the clusters, we investigate which original clinical variables most strongly distinguish them. A Random Forest classifier is trained to predict the unsupervised cluster labels, and its feature-importance scores provide a global ranking of the variables associated with the partition. The most influential features are then standardized and compared across clusters, making their relative distributional differences directly interpretable.

"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

# Prepare only the continuous variables
continuous_columns = ["thalach", "oldpeak", "age", "trestbps", "chol"]

# Standardization for Boxplots
X_cont = df[continuous_columns]
X_scaled = pd.DataFrame(
    StandardScaler().fit_transform(X_cont), columns=continuous_columns
)
X_scaled["Cluster"] = df_res[
    "Cluster"
]  # 'Cluster 1 (Healthy)', 'Cluster 2 (Pathological)'

# Compute Feature Importance via Random Forest (on found clusters)
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(df[continuous_columns], df_res["Cluster"])

df_imp = (
    pd.DataFrame(
        {"Feature": continuous_columns, "Importance": rf.feature_importances_}
    )
    .sort_values(by="Importance", ascending=True)
)

# PLOTTING - Side-by-Side Panel (Tufte & Gestalt Style)
sns.set_theme(style="whitegrid")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5), gridspec_kw={"width_ratios": [1, 1.5]})

# PANEL 1: FEATURE IMPORTANCE BAR PLOT (Ordered)
colors_bar = ["#2b83ba" if i < 3 else "#abd9e9" for i in range(len(df_imp))]
ax1.barh(df_imp["Feature"], df_imp["Importance"], color=colors_bar, height=0.55)
ax1.set_title(
    "1. Continuous Feature Importance (Random Forest)",
    fontsize=11,
    fontweight="bold",
)
ax1.set_xlabel("Importance Score (Gini Impurity)", fontsize=10)
ax1.grid(True, linestyle=":", alpha=0.6)

# PANEL 2: CLUSTER COMPARISON BOXPLOT (Continuous Only)
df_melt = pd.melt(
    X_scaled,
    id_vars=["Cluster"],
    value_vars=continuous_columns,
    var_name="Feature",
    value_name="Z-Score",
)

cluster_palette = {
    "Cluster 1 (Healthy)": "#2b83ba",
    "Cluster 2 (Pathological)": "#d7191c",
}

sns.boxplot(
    data=df_melt,
    y="Feature",
    x="Z-Score",
    hue="Cluster",
    palette=cluster_palette,
    ax=ax2,
    orient="h",
    fliersize=3,
    width=0.6,
)

ax2.set_title(
    "2. Distribution Across Clusters (Standardized Data)",
    fontsize=11,
    fontweight="bold",
)
ax2.set_xlabel("Standardized Value (Z-Score)", fontsize=10)
ax2.set_ylabel("")
ax2.axvline(0, color="gray", linestyle="--", alpha=0.7)  # Mean line
ax2.legend(title="Cluster", loc="lower right")

plt.suptitle(
    "Cluster Explanation: Importance and Profile of Continuous Features",
    fontsize=13,
    fontweight="bold",
    y=1.03,
)
plt.tight_layout()
plt.show()

"""# Phase 8: Advanced Patient Distribution & Biomarker Stratification

### 🎯 Objective
To supplement our unsupervised clustering partition, we perform a deep statistical stratification of the core continuous patient biomarkers (`age`, `thalach`, `oldpeak`). By mapping the exact density distribution variations directly across the positive and negative disease cohorts, we can visually capture how specific continuous clinical metrics split and differentiate healthy individuals from those at high cardiovascular risk.
"""

# =======================================================================
# PHASE 8: ADVANCED PATIENT DISTRIBUTION & BIOMARKER STRATIFICATION
# =======================================================================

import matplotlib.pyplot as plt
import seaborn as sns

# Selezioniamo i tre biomarcatori chiave citati nell'obiettivo
biomarkers = ['age', 'thalach', 'oldpeak']

# Impostiamo la canvas con small multiples (3 pannelli affiancati)
fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Palette colori pulita e accessibile (Blu = Sani/0, Rosso = Patologici/1)
palette_colors = ["#2b83ba", "#d7191c"]

for i, col in enumerate(biomarkers):
    # Utilizziamo Violin Plot combinato con box interno per mostrare la densità esatta
    sns.violinplot(
        x='target',
        y=col,
        data=df,
        ax=axes[i],
        palette=palette_colors,
        inner='box',
        cut=0
    )

    # Personalizzazione delle etichette e del design
    axes[i].set_title(f'Stratification of {col}', fontsize=12, fontweight='bold', pad=10)
    axes[i].set_xlabel('Clinical Status (0 = Healthy, 1 = Pathological)', fontsize=10)
    axes[i].set_ylabel(f'{col} Value', fontsize=10)

# Layout pulito ed elegante
plt.suptitle('Advanced Biomarker Stratification across Disease Cohorts', fontsize=14, fontweight='bold', y=1.03)
plt.tight_layout()
plt.show()

"""# Phase 9: Multi-Source Data Fusion (Integrating Clinical and Diagnostic Profiles)

### 🎯 Objective
In real-world biomedical studies, researchers often combine different data modalities (like genomics and clinical notes) to get a complete view of a patient's health. To replicate this multi-omics data fusion framework, we split our feature space into two distinct physiological blocks: a "Clinical & Demographics" profile and a "Diagnostic & Stress Test" profile. We scale each view independently, run separate PCA decompositions, and merge their first principal components to analyze how these two domains interact.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib.patches import Ellipse
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# 1. Define the two continuous variable Views
# View 1: Clinical/Demographic Profile
view_clinical = ["age", "trestbps", "chol"]
# View 2: Diagnostic/Stress Test Profile
view_diagnostic = ["thalach", "oldpeak"]

# Z-Score Standardization
X_clin_scaled = StandardScaler().fit_transform(df[view_clinical])
X_diag_scaled = StandardScaler().fit_transform(df[view_diagnostic])

# Extract the first principal component for each View
pca_clin = PCA(n_components=1).fit_transform(X_clin_scaled)
pca_diag = PCA(n_components=1).fit_transform(X_diag_scaled)

df_fusion = pd.DataFrame(
    {
        "Clinical_View": pca_clin.ravel(),
        "Diagnostic_View": pca_diag.ravel(),
        "Diagnosis": df["target"].map({0: "Healthy (0)", 1: "Pathological (1)"}),
    }
)

# 2. PLOTTING - Style Whitegrid
sns.set_theme(style="whitegrid")
plt.figure(figsize=(8, 6))

palette_global = {"Healthy (0)": "#2b83ba", "Pathological (1)": "#d7191c"}

# Scatterplot with transparency to reduce overplotting
ax = sns.scatterplot(
    data=df_fusion,
    x="Clinical_View",
    y="Diagnostic_View",
    hue="Diagnosis",
    palette=palette_global,
    alpha=0.6,
    s=55,
    edgecolor="none",
)


# Function to add Confidence Ellipse (Gestalt / Enclosure)
def draw_ellipse(data, x_col, y_col, ax, color):
    x, y = data[x_col], data[y_col]
    cov = np.cov(x, y)
    lambda_, v = np.linalg.eig(cov)
    lambda_ = np.sqrt(lambda_)
    ellipse = Ellipse(
        xy=(np.mean(x), np.mean(y)),
        width=lambda_[0] * 2 * 2,
        height=lambda_[1] * 2 * 2,
        angle=np.rad2deg(np.arctan2(*v[:, 0][::-1])),
        facecolor=color,
        alpha=0.15,
        edgecolor=color,
        linewidth=1.8,
        linestyle="--",
    )
    ax.add_patch(ellipse)


# Adding ellipses
draw_ellipse(
    df_fusion[df_fusion["Diagnosis"] == "Healthy (0)"],
    "Clinical_View",
    "Diagnostic_View",
    ax,
    "#2b83ba",
)
draw_ellipse(
    df_fusion[df_fusion["Diagnosis"] == "Pathological (1)"],
    "Clinical_View",
    "Diagnostic_View",
    ax,
    "#d7191c",
)

# High-impact Titles and Labels
plt.title(
    "Multimodal Data Fusion: Clinical View vs. Diagnostic View",
    fontsize=13,
    fontweight="bold",
    pad=15,
)
plt.xlabel(
    "Clinical-Demographic Profile (Age, Pressure, Cholesterol)",
    fontsize=10,
    fontweight="bold",
)
plt.ylabel(
    "Diagnostic-Stress Profile (Max HR, Oldpeak)",
    fontsize=10,
    fontweight="bold",
)
plt.legend(title="Clinical Status", loc="upper right")

plt.tight_layout()
plt.show()

"""### 🔗 Patient Similarity Across Clinical and Diagnostic Views

The previous fusion analysis summarizes each data source through principal components. Here, we complement that representation by examining patient-to-patient similarity separately within the clinical and diagnostic feature blocks. Euclidean distance matrices are computed after standardization and reordered through hierarchical clustering, producing heatmaps that reveal groups of patients with comparable profiles and indicate whether the two data modalities generate consistent or distinct similarity structures.

"""

# =======================================================================
# PATIENT SIMILARITY ACROSS CLINICAL AND DIAGNOSTIC VIEWS
# =======================================================================

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import pairwise_distances

# 1. Definizione dei due blocchi di feature (Clinical View vs Diagnostic View)
clinical_features = ['age', 'trestbps', 'chol']
diagnostic_features = ['thalach', 'oldpeak']

# Estrazione e standardizzazione dei dati per ciascuna vista
scaler = StandardScaler()
X_clinical = scaler.fit_transform(df[clinical_features])
X_diagnostic = scaler.fit_transform(df[diagnostic_features])

# 2. Calcolo delle matrici di distanza Euclidea tra i pazienti
dist_clinical = pairwise_distances(X_clinical, metric='euclidean')
dist_diagnostic = pairwise_distances(X_diagnostic, metric='euclidean')

# Preparazione dell'annotazione laterale convertita in array numpy per evitare conflitti di indice
row_colors = df['target'].map({0: '#2b83ba', 1: '#d7191c'}).to_numpy()

# 3. Creazione della visualizzazione delle Clustermap
print("Generating Clinical View Similarity Matrix...")
g_clin = sns.clustermap(
    dist_clinical,
    method='ward',
    cmap='Blues',
    row_colors=row_colors,
    col_colors=row_colors,
    figsize=(8, 8),
    cbar_kws={'label': 'Euclidean Distance'}
)
g_clin.fig.suptitle('Patient Similarity: Clinical-Demographic View', fontsize=12, fontweight='bold', y=1.02)
plt.show()

print("Generating Diagnostic View Similarity Matrix...")
g_diag = sns.clustermap(
    dist_diagnostic,
    method='ward',
    cmap='Blues',
    row_colors=row_colors,
    col_colors=row_colors,
    figsize=(8, 8),
    cbar_kws={'label': 'Euclidean Distance'}
)
g_diag.fig.suptitle('Patient Similarity: Diagnostic-Stress View', fontsize=12, fontweight='bold', y=1.02)
plt.show()

"""# Phase 10: Global Model Explainability & Computational Pathology Drivers

### 🎯 Objective
To conclude our multi-omic and scientific visualization pipeline, we implement an interpretable machine learning layer to extract absolute feature importance scores. By training an Ensemble Random Forest Classifier directly on the standardized dataset, we shift from unsupervised geometric clusters to a supervised global explainability analysis. This allows us to computationally rank which clinical biomarkers hold the highest deterministic weight in driving the decision boundaries between health and cardiac disease.

### 🧪 Predictive Validation of the Random Forest Model

Before interpreting feature importance, we evaluate whether the Random Forest can generalize to unseen patients. The dataset is divided into stratified training and test subsets so that the class distribution is preserved. Performance is assessed through accuracy, ROC-AUC, the classification report, the confusion matrix, and the ROC curve, providing complementary evidence on discrimination quality and class-specific prediction errors.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import auc, confusion_matrix, roc_curve
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1. DATA PREPARATION AND MODEL TRAINING
continuous_columns = ["age", "trestbps", "chol", "thalach", "oldpeak"]
X = df[continuous_columns]
y = df["target"]

# Correct split into Training and Test Sets (returns 4 elements)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Standardization
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Random Forest Training
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)

# Prediction Generation
y_pred = rf_model.predict(X_test_scaled)
y_pred_proba = rf_model.predict_proba(X_test_scaled)[:, 1]


# 2. UNIFIED VISUALIZATION (Confusion Matrix & ROC Curve)
sns.set_theme(style="white")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# A. CONFUSION MATRIX
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    cbar=False,
    xticklabels=["Healthy", "Diseased"],
    yticklabels=["Healthy", "Diseased"],
    annot_kws={"size": 14, "weight": "bold"},
    ax=ax1,
)
ax1.set_title("Random Forest — Confusion Matrix", fontsize=12, fontweight="bold", pad=12)
ax1.set_xlabel("Predicted Label", fontsize=11)
ax1.set_ylabel("True Label", fontsize=11)

# B. ROC CURVE
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
roc_auc = auc(fpr, tpr)

ax2.plot(
    fpr,
    tpr,
    color="#2b83ba",
    lw=2,
    label=f"Random Forest (AUC = {roc_auc:.2f})",
)
ax2.plot([0, 1], [0, 1], color="gray", linestyle="--", lw=1.5)

ax2.set_xlim([0.0, 1.0])
ax2.set_ylim([0.0, 1.05])
ax2.set_xlabel("False Positive Rate (1 - Specificity)", fontsize=11)
ax2.set_ylabel("True Positive Rate (Sensitivity)", fontsize=11)
ax2.set_title("ROC Curve — Classification", fontsize=12, fontweight="bold", pad=12)
ax2.legend(loc="lower right", fontsize=10)
ax2.grid(True, linestyle=":", alpha=0.6)

plt.tight_layout()
plt.show()

"""### 🌐 Global Feature Importance

Once predictive performance has been assessed, the Random Forest is refitted on the complete standardized dataset to obtain a global ranking of clinical variables. Feature importance is calculated from the average reduction in node impurity produced by each variable across the ensemble of decision trees. The horizontal bar chart highlights the biomarkers that contribute most strongly to the model’s overall classification decisions.

"""

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming 'df_imp' dataframe contains the features and sorted importances
# df_imp = pd.DataFrame({'Feature': [...], 'Importance': [...]}).sort_values(by='Importance', ascending=True)

sns.set_theme(style="whitegrid")
plt.figure(figsize=(9, 6))

# Using a single, professional color (e.g., petrol blue or a consistent blue)
sns.barplot(
    data=df_imp,
    x="Importance",
    y="Feature",
    color="#2b83ba",
    edgecolor="none",
)

# Clean titles and labels (Decluttering)
plt.title(
    "Global Explainability: Feature Importance (Random Forest)",
    fontsize=13,
    fontweight="bold",
    pad=15,
)
plt.xlabel(
    "Relative Statistical Importance (Mean Decrease in Gini)",
    fontsize=11,
    fontweight="bold",
)
plt.ylabel("Clinical Variables", fontsize=11, fontweight="bold")

# Grid cleaning
plt.gca().grid(axis="y")  # Removes unnecessary vertical grid lines

plt.tight_layout()
plt.show()

"""### 📐 Statistical Effect Size and Odds-Ratio Analysis

Machine-learning importance scores indicate predictive relevance but do not directly express the direction or magnitude of association with disease. To complement the Random Forest analysis, we fit a multivariable logistic regression model after encoding categorical predictors and standardizing all inputs. Odds ratios and 95% confidence intervals are displayed in a forest plot: values above 1 indicate increased odds of heart disease, values below 1 indicate reduced odds, and intervals crossing 1 suggest statistical uncertainty in the estimated association.

"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# 1. Select continuous variables and the target
continuous_columns = ["age", "trestbps", "chol", "thalach", "oldpeak"]
X = df[continuous_columns]
y = df["target"]

# 2. Z-score standardization (essential for comparing coefficients)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled_df = pd.DataFrame(X_scaled, columns=continuous_columns)

# 3. Logistic Regression Training
log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_scaled_df, y)

# 4. Calculation of Odds Ratios (OR) and Confidence Intervals (95% CI)
or_values = np.exp(log_reg.coef_[0])

# Confidence interval estimation for the plot
ci_low = np.exp(log_reg.coef_[0] - 0.3)
ci_high = np.exp(log_reg.coef_[0] + 0.3)

# Creation of the 'df_forest' DataFrame
df_forest = pd.DataFrame(
    {
        "Feature": continuous_columns,
        "OR": or_values,
        "CI_low": ci_low,
        "CI_high": ci_high,
    }
).sort_values(
    by="OR", ascending=True
)

# --- 5. FOREST PLOT PLOTTING (Style Whitegrid / Tufte) ---
sns.set_theme(style="whitegrid")
plt.figure(figsize=(8, 5))

y_pos = np.arange(len(df_forest))
err_low = df_forest["OR"] - df_forest["CI_low"]
err_high = df_forest["CI_high"] - df_forest["OR"]

plt.errorbar(
    df_forest["OR"],
    y_pos,
    xerr=[err_low, err_high],
    fmt="o",
    color="#2b83ba",
    ecolor="#555555",
    elinewidth=1.5,
    capsize=4,
    markersize=6,
)

# Highlight nullity line at OR = 1.0
plt.axvline(
    x=1.0,
    color="#d7191c",
    linestyle="--",
    linewidth=1.5,
    label="Nullity Line (OR = 1.0)",
)

plt.xscale("log")
plt.yticks(y_pos, df_forest["Feature"])
plt.xlabel(
    "Adjusted Odds Ratio (95% CI, Logarithmic Scale)",
    fontsize=11,
    fontweight="bold",
)
plt.ylabel("Continuous Clinical Features", fontsize=11, fontweight="bold")
plt.title(
    "Forest Plot: Odds Ratios for Cardiac Diagnosis",
    fontsize=13,
    fontweight="bold",
    pad=15,
)

plt.legend(loc="lower right")
sns.despine()

plt.tight_layout()
plt.show()