# -*- coding: utf-8 -*-
"""Scientific_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BN1X3wDDECujlQ9Vgj35_hnoz2DTRncB

# Phase 0: Pipeline Initialization, Data Sourcing & Architectural Setup

### 🎯 Overview & Action Plan
Before executing any analytical or computational task, establishing a rigid, warning-free environment and securing data alignment is paramount. This initial phase sets up our scientific computing ecosystem.

Our architectural plan for this phase consists of:
1. **Workspace Anchoring:** Mounting the remote Google Drive repository or resolving local paths to ensure persistent data streams.
2. **Environment Stabilization:** Silencing core runtime warnings (`FutureWarning` / `UserWarning`) to guarantee clean, professional reporting.
3. **Multi-Algorithmic Dependency Loading:** Importing specialized modules for mathematical computing (`numpy`, `pandas`), scientific visualization (`seaborn`, `matplotlib`), hierarchical structures (`scipy`), statistical modeling (`statsmodels`), and machine learning (`sklearn`).
4. **Data Sourcing & Raw Shape Auditing:** Dynamically locating and ingesting the raw clinical dataset (`heart.csv`) while verifying its initial matrix dimensions and feature attributes.
"""

import os
import warnings
from pathlib import Path

# Disable future warnings to keep the output clean and professional during the presentation
warnings.filterwarnings('ignore', category=FutureWarning)

# Core libraries for data science
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Modules for statistics and clustering
from scipy.cluster.hierarchy import linkage, dendrogram # For hierarchical clustering
from scipy.stats import chi2 # For advanced statistical calculations (e.g. covariance ellipses)
import statsmodels.api as sm # For statistical inference (e.g. logistic regression for odds ratios)

# Scikit-learn: machine learning and preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import (
    pairwise_distances, silhouette_score,
    adjusted_rand_score, normalized_mutual_info_score,
    confusion_matrix, accuracy_score, roc_auc_score,
    roc_curve, classification_report
)
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Set a clean and consistent aesthetic theme for all seaborn plots
sns.set_theme(style='whitegrid')

# Set the seed to ensure full mathematical reproducibility of the experiment
RANDOM_STATE = 42

# Dynamic file system management (colab or local)
# Attempt to automatically mount google drive if the notebook is running on colab
# The try-except block prevents the code from crashing if executed locally (e.g. classic jupyter)
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=False)
except Exception:
    pass # Ignore the error if we are not in a google colab environment

# Define a list of probable paths where the dataset might be located
candidate_paths = [
    '/content/drive/MyDrive/heart.csv',
    '/content/heart.csv',
    '/mnt/data/heart.csv',
]

# Search for the first valid path among the candidates
path = next((p for p in candidate_paths if os.path.exists(p)), None)

# Emergency fallback: if the file is not found automatically,
# it triggers a prompt asking the user to upload it manually
if path is None:
    try:
        from google.colab import files
        uploaded = files.upload()
        if not uploaded:
            raise FileNotFoundError('No file uploaded.')
        # Get the name of the newly uploaded file
        path = next(iter(uploaded.keys()))
    except Exception as e:
        raise FileNotFoundError(
            'heart.csv not found. Put it in MyDrive, upload it to Colab, or update candidate_paths.'
        ) from e

# Loading and initial data audit
df_raw = pd.read_csv(path)

# Print basic information to verify that the data ingestion was successful
print('Loaded:', path)
print('Raw shape:', df_raw.shape)
print('Columns:', df_raw.columns.tolist())

"""# Phase 1: Data Quality Audit & Duplicate Removal

### 🎯 Objective & Methodology
Before injecting data into descriptive statistics, dimensionality reduction, or machine learning pipelines, a rigorous quality audit is mandatory. This phase ensures data integrity, checks for missing entries that could compromise matrix operations, and eliminates redundant rows that might distort probability estimates or bias downstream models.

Our pipeline implements:
1. **Duplicate Record Audit:** Explicitly quantifying total rows, exact repeating vectors, and unique patient profiles within the raw input space.
2. **Matrix Completeness Check:** Verifying whether any missing values exist across the clinical feature vectors.
3. **Dataset Consolidation:** Stripping out exact duplicate observations to yield a clean, unique cohort, followed by an immediate verification of the resulting target class distribution.
"""

# Count the number of exact duplicate rows in the raw dataset
duplicate_count = int(df_raw.duplicated().sum())

# Calculate the number of unique patient records
unique_count = int(len(df_raw.drop_duplicates()))

# Print a formatted audit report for data quality inspection
print('=' * 65)
print('DUPLICATE RECORD AUDIT')
print('=' * 65)
print(f'Total rows:       {len(df_raw)}')
print(f'Duplicate rows:   {duplicate_count}')
print(f'Unique rows:      {unique_count}')
print('=' * 65)

# Check for missing values across all columns
missing = df_raw.isna().sum()

# Display columns with missing data or confirm none exist
print(); print('Missing values:')
print(missing[missing > 0] if missing.sum() else 'None')

# Create the consolidated clean dataset by dropping duplicates and resetting the index
df = df_raw.drop_duplicates().reset_index(drop=True)

# Verify the final dimensions and check the balance of the target variable
print(); print('Clean dataset shape:', df.shape)
print('Remaining duplicates:', int(df.duplicated().sum()))
print(); print('Target distribution:')
print(df['target'].value_counts().sort_index())

"""### Target Class Distribution & Balance Assessment

Before proceeding with exploratory data analysis or model training, inspecting the distribution of the target variable is essential to identify potential class imbalance.

Our pipeline implements:
1. **Class Frequency Extraction:** Computing the exact sample counts for each target category (`0` and `1`) following initial data cleaning and duplicate removal.
2. **Bar Plot Visualization:** Rendering a clean bar chart with explicit count annotations positioned above each bar for immediate visual clarity.
3. **Imbalance Evaluation:** Assessing the relative proportion of positive versus negative cases, which informs downstream choices regarding evaluation metrics (such as ROC-AUC and F1-score) and handling strategies.
"""

# Compute exact frequency counts for each target class in sorted order
class_counts = df['target'].value_counts().sort_index()

# Initialize figure canvas for the bar chart
plt.figure(figsize=(6, 4))
ax = sns.barplot(
    x=['Class 0', 'Class 1'],
    y=class_counts.values,
    color='#6baed6'
)

# Annotate each bar with its exact patient count value for immediate clarity
for i, v in enumerate(class_counts.values):
    ax.text(i, v + 2, str(v), ha='center', va='bottom', fontweight='bold')

# Configure axis labels, title, and clean up unnecessary spines
plt.ylabel('Number of patients')
plt.xlabel('Target class')
plt.title('Target Class Distribution after Duplicate Removal', fontweight='bold')
sns.despine()
plt.tight_layout()
plt.show()

"""## Phase 2 — Distributional Audit: One Boxplot per Continuous Feature

Before applying coordinate transformations or space alignment workflows, evaluating the distributional properties and presence of extreme values in continuous features is an essential preliminary step. As part of our exploratory data analysis and data cleaning pipeline, this framework utilizes multi-panel boxplots combined with jittered stripplots to screen key continuous parameters—specifically `age`, resting blood pressure (`trestbps`), serum cholesterol (`chol`), maximum heart rate (`thalach`), and ST depression (`oldpeak`)—stratified across target classes.

Each continuous variable is plotted in its own dedicated panel with its specific unit of measurement, avoiding the distortion of scale that occurs when plotting heterogeneous units on a shared axis.

Our pipeline implements:
1. **Group-wise Distributional Visualization:** Stratifying each continuous parameter by target class to inspect median shifts, interquartile ranges, and overall spread.
2. **Stripplot Overlay:** Displaying individual observation points with transparency and jitter to reveal underlying sample density and individual data points.
3. **Statistical Outlier Screening:** Computing interquartile range (IQR) boundaries ($1.5 \times \text{IQR}$) per group to quantitatively flag statistical distributional outliers. Because extreme values often correspond to valid physiological extremes rather than data errors, they are quantified and inspected rather than automatically removed.
"""

# Define continuous clinical columns and their corresponding descriptive axis units
continuous_columns = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
units = {
    'age': 'Years',
    'trestbps': 'Resting blood pressure',
    'chol': 'Serum cholesterol',
    'thalach': 'Maximum heart rate',
    'oldpeak': 'ST depression (oldpeak)'
}

# Initialize a multi-panel figure with a 2x3 grid layout for individual feature boxplots
fig, axes = plt.subplots(2, 3, figsize=(15, 9))
axes = axes.ravel()
palette = ['#2b83ba', '#d95f02']

# Iterate through each continuous feature to plot stratified boxplots and jittered stripplots
for i, col in enumerate(continuous_columns):
    sns.boxplot(
        data=df, x='target', y=col, ax=axes[i],
        palette=palette, width=0.45, fliersize=4
    )
    sns.stripplot(
        data=df, x='target', y=col, ax=axes[i],
        color='black', alpha=0.20, size=2.5, jitter=0.18
    )
    axes[i].set_title(f'{col}: distribution by target class', fontweight='bold')
    axes[i].set_xlabel('Target class (0 / 1)')
    axes[i].set_ylabel(units[col])
    axes[i].grid(axis='y', linestyle=':', alpha=0.35)

# Hide the extra unused subplot axis on the grid
axes[-1].axis('off')
plt.suptitle('Distributional Audit — One Boxplot per Continuous Feature',
             fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.show()

# Perform an optional numerical audit to compute group-wise IQR boundaries and count outliers
rows = []
for col in continuous_columns:
    for target_value, g in df.groupby('target'):
        q1, q3 = g[col].quantile([0.25, 0.75])
        iqr = q3 - q1
        lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr
        n_out = int(((g[col] < lo) | (g[col] > hi)).sum())
        rows.append([col, int(target_value), lo, hi, n_out])

# Compile outlier audit results into a dataframe and display rounded values
outlier_audit = pd.DataFrame(
    rows, columns=['Feature', 'Target', 'Lower_IQR_bound', 'Upper_IQR_bound', 'Outlier_count']
)
display(outlier_audit.round(2))

"""## Phase 3 — Correlation Among Continuous Features

Pearson product-moment correlation coefficients are computed exclusively for the five continuous variables (`age`, `trestbps`, `chol`, `thalach`, `oldpeak`).

Our pipeline implements:
1. **Targeted Bivariate Association Mapping:** Restricting the correlation architecture to continuous parameters prevents the inclusion of categorical or binary attributes, ensuring meaningful linear correlation metrics.
2. **Redundancy Elimination:** Applying a strict upper-triangle mask to filter out symmetrical duplication.
3. **Diverging Heatmap Visualization:** Utilizing a balanced colormap (`RdBu_r`) centered at zero to clearly display positive and negative linear dependencies across features before linear dimensionality reduction or modeling.
"""

# Computing Pearson Correlation Matrix
corr = df[continuous_columns].corr(method='pearson')

# Creating an upper-triangle mask to avoid redudancy
mask = np.triu(np.ones_like(corr, dtype=bool))

# Plotting the diverging heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(
    corr, mask=mask, annot=True, fmt='.2f',
    cmap='RdBu_r', center=0, vmin=-1, vmax=1,
    square=True, linewidths=0.7,
    cbar_kws={'label': 'Pearson correlation (r)', 'shrink': 0.8}
)

# Set a bold title, optimize the layout spacing, and render the final plot
plt.title('Correlation Matrix — Continuous Clinical Features', fontweight='bold', pad=12)
plt.tight_layout()
plt.show()

"""## Phase 4 — Standardization for PCA and Distance-Based Models

Distance-based algorithms (such as K-Means) and linear transformations (such as PCA) are sensitive to the magnitude and units of measurement of individual variables. To prevent features with larger numeric scales (e.g., serum cholesterol in mg/dL) from dominating those with smaller scales (e.g., ST depression), the continuous feature space is standardized using a Z-score transformation.

Our pipeline implements:
1. **Feature Separation & Target Isolation:** Segregating the five continuous clinical variables from the ground-truth target vector.
2. **Z-score Transformation:** Centering and scaling each continuous feature to a mean of 0 and a standard deviation of 1 via `StandardScaler`.
3. **Empirical Verification:** Generating a summary dataframe to programmatically verify that post-scaling means approach zero and standard deviations equal unity across all feature dimensions.
"""

# Isolate continuous features and target vector
X_cont = df[continuous_columns].copy()
y = df['target'].copy()

# Apply z-score standardization (mean=0, standard deviation=1)
scaler_cont = StandardScaler()
X_scaled = scaler_cont.fit_transform(X_cont)

# Create a dataframe to empirically verify scaling outcomes
scaled_df = pd.DataFrame(X_scaled, columns=continuous_columns)
verification = pd.DataFrame({
    'mean_after_scaling': scaled_df.mean(),
    'std_after_scaling': scaled_df.std(ddof=0)
})

# Display the verification summary rounded to 4 decimal places
display(verification.round(4))

"""## Phase 5 — PCA: Multivariate Linear Structure

While pairwise correlations examine variables strictly in isolation, Principal Component Analysis (PCA) captures the global multivariate covariance structure of the dataset through orthogonal linear components that maximize explained variance.

In this analytical pipeline, PCA serves as a foundational linear dimensionality reduction step. It rigorously compresses the high-dimensional continuous feature space onto principal axes, eliminating mathematical redundancy and isolating the underlying latent structure to prepare the data for downstream unsupervised clustering.

## Phase 5.1 — PCA: Scree Plot & Explained Variance Analysis

To quantify how much global variance is captured by each orthogonal dimension, we fit a full Principal Component Analysis model on the standardized continuous features.

Our pipeline implements:
1. **Variance Decomposition:** Computing the individual percentage of explained variance for each principal component derived from the covariance matrix eigenvalues.
2. **Cumulative Variance Tracking:** Calculating cumulative sums to identify how many components are required to capture the vast majority of the system's total variability.
3. **Dual-Axis Visualization:** Plotting individual explained variance via bar charts alongside cumulative variance curves featuring an 80% reference threshold line.
4. **Automated Dimensionality Metric:** Programmatically determining the exact number of principal components needed to cross the 80% cumulative variance threshold.
"""

# Fit full pca model on the standardized continuous features
pca_full = PCA()
pca_full.fit(X_scaled)

# Compute individual and cumulative explained variance percentages
explained = pca_full.explained_variance_ratio_ * 100
cumulative = np.cumsum(explained)
pcs = np.arange(1, len(explained) + 1)

# Set up dual-axis figure for individual bars and cumulative line
fig, ax1 = plt.subplots(figsize=(9, 5))
ax1.bar(pcs, explained, color='#8da0cb', width=0.62)
ax1.set_xlabel('Principal component')
ax1.set_ylabel('Individual explained variance (%)')
ax1.set_xticks(pcs)
ax1.grid(axis='y', linestyle=':', alpha=0.35)

# Create secondary axis for cumulative variance curve and 80% threshold line
ax2 = ax1.twinx()
ax2.plot(pcs, cumulative, marker='o', color='#d95f02', linewidth=2)
ax2.axhline(80, color='gray', linestyle='--', linewidth=1.2)
ax2.set_ylabel('Cumulative explained variance (%)')
ax2.set_ylim(0, 105)

plt.title('PCA Scree Plot and Cumulative Explained Variance', fontweight='bold')
fig.tight_layout()
plt.show()

# Variance and display the variance summary table rounded to 2 decimal places
variance_table = pd.DataFrame({
    'PC': [f'PC{i}' for i in pcs],
    'Explained_variance_%': explained,
    'Cumulative_%': cumulative
})
display(variance_table.round(2))

# Programmatically determine components required to cross the 80% threshold
n80 = int(np.argmax(cumulative >= 80) + 1)
print(f'Components required to exceed 80% cumulative variance: {n80}')

"""## Phase 5.2 — PCA: 2D Projection & Feature Biplot

To visualize how patients distribute in the reduced latent space and how individual clinical variables drive this layout, we project the standardized continuous features onto the first two principal components (`PC1` and `PC2`).

Our pipeline implements:
1. **Dimensionality Reduction via Linear PCA:** Extracting the top 2 principal components to map the multivariate data into a 2D scatter space.
2. **Class Stratification:** Color-coding patient projections by their target class (`Class 0` vs `Class 1`) to inspect class separation and spatial overlap.
3. **Feature Loadings Mapping:** Calculating eigenvector loadings to plot directional arrows (scaled for visual clarity) representing the contribution and correlation of each original continuous variable with respect to `PC1` and `PC2`.
4. **Annotated Biplot Generation:** Combining the scatter projection of observations with feature vectors and quadrant gridlines to facilitate simultaneous interpretation of patient profiles and biomarker drivers.
"""

# Fit 2-component pca and extract loadings and explained variance ratios
pca_2d = PCA(n_components=2)
X_pca = pca_2d.fit_transform(X_scaled)
loadings = pca_2d.components_.T
var_pc1, var_pc2 = pca_2d.explained_variance_ratio_ * 100

# Build dataframe containing principal components and mapped target labels
pca_df = pd.DataFrame(X_pca, columns=['PC1', 'PC2'])
pca_df['Target'] = y.map({0: 'Class 0', 1: 'Class 1'})

# Initialize scatter plot for patient projections on pc1 and pc2
plt.figure(figsize=(9, 7))
sns.scatterplot(
    data=pca_df, x='PC1', y='PC2', hue='Target',
    palette=['#2b83ba', '#d95f02'], alpha=0.60, s=48, edgecolor='none'
)

# Overlay feature load vectors and text labels using scaled eigenvectors
arrow_scale = 3.2
for i, feature in enumerate(continuous_columns):
    x_l = loadings[i, 0] * arrow_scale
    y_l = loadings[i, 1] * arrow_scale
    plt.arrow(0, 0, x_l, y_l, color='#222222',
              linewidth=1.4, head_width=0.09, alpha=0.9)
    plt.text(x_l * 1.12, y_l * 1.12, feature,
             ha='center', va='center', fontweight='bold', fontsize=10,
             bbox=dict(boxstyle='round,pad=0.2', facecolor='white', alpha=0.82, edgecolor='none'))

# Format plot layout with reference gridlines, labels, and title
plt.axhline(0, color='gray', linestyle='--', linewidth=0.8)
plt.axvline(0, color='gray', linestyle='--', linewidth=0.8)
plt.xlabel(f'PC1 ({var_pc1:.1f}% explained variance)')
plt.ylabel(f'PC2 ({var_pc2:.1f}% explained variance)')
plt.title('PCA Biplot — Continuous Features', fontweight='bold')
plt.legend(title='Target class')
plt.tight_layout()
plt.show()

"""## Phase 5.3 — PCA: Group Projections & 95% Confidence Ellipses

To evaluate the statistical spread and distribution overlap of each class within the principal component space, we augment our 2D scatter projection with formal covariance ellipses.

Our pipeline implements:
1. **Bivariate Covariance Estimation:** Calculating group-specific means and covariance matrices directly from the `PC1` and `PC2` coordinates for each target class.
2. **Eigen-Decomposition:** Determining eigenvalues and eigenvectors of the covariance matrices to define the orientation and principal axes of data dispersion.
3. **Chi-Square Scale Adjustment:** Utilizing the inverse cumulative distribution function of the chi-squared distribution (`chi2.ppf`) with two degrees of freedom ($\text{df}=2$) to scale the ellipse accurately for a 95% confidence level.
4. **Geometric Ellipse Patch Generation:** Constructing and overlaying custom `matplotlib.patches.Ellipse` boundary vectors with semi-transparent face colors and dashed borders onto the axes to visually delineate cluster dispersion.

### Interpretation

The covariance ellipses are used as descriptive summaries of the spatial distribution of the two target classes. Although the groups show a shift in their position within the PCA plane, substantial overlap remains between their distributions.

Therefore, the first two principal components reveal only partial class separation and should not be interpreted as providing a clear diagnostic boundary.g
"""

from matplotlib.patches import Ellipse

# Define helper function to calculate and draw bivariate confidence ellipses
def add_covariance_ellipse(x, y, ax, color, confidence=0.95):
    xy = np.column_stack([x, y])
    cov = np.cov(xy, rowvar=False)
    mean = xy.mean(axis=0)

    # Perform eigen-decomposition of the covariance matrix
    eigvals, eigvecs = np.linalg.eigh(cov)
    order = eigvals.argsort()[::-1]
    eigvals = eigvals[order]
    eigvecs = eigvecs[:, order]

    # Scale ellipse dimensions using chi-squared quantiles for df=2
    scale = np.sqrt(chi2.ppf(confidence, df=2))
    width, height = 2 * scale * np.sqrt(eigvals)
    angle = np.degrees(np.arctan2(eigvecs[1, 0], eigvecs[0, 0]))

    # Initialize figure and target color palette mapping
    ellipse = Ellipse(
        xy=mean, width=width, height=height, angle=angle,
        facecolor=color, edgecolor=color, alpha=0.12,
        linewidth=1.8, linestyle='--'
    )
    ax.add_patch(ellipse)

fig, ax = plt.subplots(figsize=(9, 6))
palette_target = {'Class 0': '#2b83ba', 'Class 1': '#d95f02'}

# Plot patient scatter points on pc1 and pc2 space
sns.scatterplot(
    data=pca_df, x='PC1', y='PC2', hue='Target',
    palette=palette_target, alpha=0.58, s=52, edgecolor='none', ax=ax
)

# Iterate over target classes to overlay group-wise 95% confidence ellipses
for label, color in palette_target.items():
    subset = pca_df[pca_df['Target'] == label]
    add_covariance_ellipse(subset['PC1'], subset['PC2'], ax, color, confidence=0.95)

# Configure axis labels, title, legend, and layout formatting
ax.set_xlabel(f'PC1 ({var_pc1:.1f}% explained variance)')
ax.set_ylabel(f'PC2 ({var_pc2:.1f}% explained variance)')
ax.set_title('PCA Projection with 95% Covariance Ellipses', fontweight='bold')
ax.legend(title='Target class')
plt.tight_layout()
plt.show()

"""## Phase 6 — Unsupervised Cluster Optimization: Elbow & Silhouette Analysis

Before running partitioning algorithms, determining the optimal number of clusters ($K$) is essential. To avoid subjective choices, we employ a data-driven evaluation framework testing a range of cluster sizes ($K \in [2, 8]$).

Our pipeline implements:
1. **Iterative K-Means Modeling:** Fitting multiple K-Means models over a defined range of $K$ values using robust initializations (`n_init=20`) on the standardized continuous feature space.
2. **Elbow Method (Inertia):** Tracking the within-cluster sum of squares (inertia) to identify the point where the marginal gain of adding more clusters diminishes.
3. **Silhouette Analysis:** Computing the average silhouette score for each $K$ to measure how tightly grouped the data points are within clusters compared to neighboring partitions.
4. **Automated Optimal Selection:** Programmatically identifying the $K$ value that yields the maximum average silhouette score, highlighting the best choice on a dual-panel evaluation plot alongside a comprehensive summary metric table.

### Interpretation

The selected value of K represents the best solution among the tested configurations according to the Silhouette Score. However, the magnitude of the score must also be considered: a relatively low Silhouette value indicates that the intrinsic cluster structure is only weakly to moderately separated.

Therefore, K=2 should be interpreted as the most supported partition among the tested alternatives, not as evidence of two sharply separated natural populations.
"""

# Define the range of cluster numbers to evaluate and initialize metric storage lists
k_values = list(range(2, 9))
inertias = []
silhouettes = []

# Iterate through each candidate value of K to fit KMeans and compute evaluation metrics
for k in k_values:
    model = KMeans(n_clusters=k, n_init=20, random_state=RANDOM_STATE)
    labels_k = model.fit_predict(X_scaled)
    inertias.append(model.inertia_)
    silhouettes.append(silhouette_score(X_scaled, labels_k))

# Determine the optimal K index and value corresponding to the maximum average silhouette score
best_idx = int(np.argmax(silhouettes))
best_k = k_values[best_idx]
best_silhouette = silhouettes[best_idx]

# Initialize a dual-panel figure to plot both the elbow method inertia and silhouette scores
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.6))
ax1.plot(k_values, inertias, marker='o', color='#2b83ba', linewidth=2)
ax1.set_title('Elbow Method (Inertia)', fontweight='bold')
ax1.set_xlabel('Number of clusters (K)')
ax1.set_ylabel('Within-cluster inertia')
ax1.set_xticks(k_values)
ax1.grid(linestyle=':', alpha=0.4)

ax2.plot(k_values, silhouettes, marker='o', color='#2b83ba', linewidth=2)
ax2.scatter(best_k, best_silhouette, s=90, color='#d95f02', zorder=3,
            label=f'Best silhouette: K={best_k}')
ax2.set_title('Silhouette Analysis', fontweight='bold')
ax2.set_xlabel('Number of clusters (K)')
ax2.set_ylabel('Average silhouette score')
ax2.set_xticks(k_values)
ax2.grid(linestyle=':', alpha=0.4)
ax2.legend()

plt.suptitle('Data-Driven Cluster-Number Selection', fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Compile evaluation metrics into a summary dataframe and display it rounded to four decimal places
cluster_selection = pd.DataFrame({
    'K': k_values,
    'Inertia': inertias,
    'Silhouette': silhouettes
})
display(cluster_selection.round(4))
print(f'Selected K = {best_k}; best silhouette = {best_silhouette:.3f}')

"""## Phase 7 — K-Means clustering and external agreement with the target

Once the optimal number of clusters ($K$) is determined, we fit the K-Means algorithm on the standardized five-dimensional continuous feature space. Because unsupervised cluster IDs are geometric partitions rather than medical diagnoses, they are labeled neutrally as `Cluster A`, `Cluster B`, etc.

Our pipeline implements:
1. **Unsupervised Partitioning:** Fitting the K-Means model using the selected $K$ parameter and robust initialization parameters (`n_init=20`).
2. **Neutral Label Mapping:** Assigning alphabetical cluster designations to avoid any arbitrary or misleading clinical interpretation of the unsupervised group IDs.
3. **Latent Space Projection:** Projecting the resulting cluster labels onto the 2D principal component space (`PC1` vs `PC2`) alongside the true target classes for direct visual comparison.
4. **Contingency Matrix Generation:** Building a cross-tabulation table to inspect how samples from the ground-truth classes are distributed across the unsupervised clusters.
5. **External Validation Metrics:** Quantifying the structural agreement between the unsupervised partitions and the clinical target classes using the **Adjusted Rand Index (ARI)** and **Normalized Mutual Information (NMI)**. Low metric values confirm that the geometric clusters do not directly replicate the diagnostic labels.
"""

# Fit KMeans clustering using the optimal number of clusters and predict labels
kmeans = KMeans(n_clusters=best_k, n_init=20, random_state=RANDOM_STATE)
cluster_labels = kmeans.fit_predict(X_scaled)

# Map numeric cluster IDs to neutral alphabetical names (e.g., Cluster A, Cluster B)
cluster_name_map = {i: f'Cluster {chr(65+i)}' for i in range(best_k)}
cluster_names = pd.Series(cluster_labels).map(cluster_name_map)

# Copy PCA dataframe and append the assigned cluster labels
cluster_df = pca_df.copy()
cluster_df['Cluster'] = cluster_names.values

# Generate a cross-tabulation contingency matrix between target classes and cluster labels
contingency = pd.crosstab(
    y.map({0: 'Class 0', 1: 'Class 1'}),
    cluster_names,
    rownames=['Target class'], colnames=['K-Means cluster']
)

# Initialize a multi-panel figure layout comparing target classes, cluster projections, and contingency heatmap
fig = plt.figure(figsize=(14, 5))
gs = fig.add_gridspec(1, 3, width_ratios=[1, 1, 0.75])
ax1, ax2, ax3 = fig.add_subplot(gs[0]), fig.add_subplot(gs[1]), fig.add_subplot(gs[2])

# Plot left panel: patient data points colored by true target classes for visual comparison
sns.scatterplot(
    data=cluster_df, x='PC1', y='PC2', hue='Target',
    palette=palette_target, alpha=0.58, s=40, edgecolor='none', ax=ax1
)
ax1.set_title('Target Classes (for comparison)', fontweight='bold')
ax1.set_xlabel(f'PC1 ({var_pc1:.1f}%)')
ax1.set_ylabel(f'PC2 ({var_pc2:.1f}%)')

# Define custom color palette for the unsupervised clusters
cluster_palette = {name: color for name, color in zip(sorted(cluster_df['Cluster'].unique()), ['#5e81ac','#e07a5f','#81b29a','#f2cc8f','#9c89b8','#4d908e','#f8961e','#577590'])}

# Plot middle panel: patient data points projected onto PC space colored by unsupervised cluster labels
sns.scatterplot(
    data=cluster_df, x='PC1', y='PC2', hue='Cluster',
    palette=cluster_palette, alpha=0.62, s=40, edgecolor='none', ax=ax2
)
ax2.set_title('K-Means Labels Projected on PCA', fontweight='bold')
ax2.set_xlabel(f'PC1 ({var_pc1:.1f}%)')
ax2.set_ylabel('')

# Plot right panel: heatmap visualization of the contingency matrix
sns.heatmap(contingency, annot=True, fmt='d', cmap='Blues', cbar=False, ax=ax3)
ax3.set_title('Contingency Table', fontweight='bold')

plt.suptitle(
    'Unsupervised Clustering vs Target',
    fontweight='bold', y=1.02
)
plt.tight_layout()
plt.show()

# Display the contingency table dataframe
display(contingency)

"""### 7.1 — Agreement Between Unsupervised Clusters and the Target

Because the K-Means algorithm partitions the latent space completely blind to the actual clinical diagnoses, we must quantify the degree of overlap between this geometric grouping and the ground truth. To achieve this, we employ two rigorous, label-invariant external validation metrics:
Adjusted Rand Index (ARI): Measures the absolute similarity between the two data partitions, statistically adjusted for chance grouping.
Normalized Mutual Information (NMI): An information-theoretic measure quantifying the mutual dependence between the geometric clusters and the diagnostic labels.
For both metrics, a score approaching 1.0 indicates perfect structural isomorphism, whereas a value near 0.0 denotes random assignment.

Interpretation:
The observed low ARI and NMI scores are methodologically revealing. They demonstrate that while K-Means successfully isolates a natural physiological variance in the continuous feature space, this purely geometric structure does not perfectly mirror the complex clinical diagnosis. This structural divergence mathematically justifies the necessity of our subsequent supervised architecture (Late Fusion) to establish precise and reliable diagnostic boundaries.
"""

# Calculate the adjusted rand index to measure partition similarity adjusted for chance
ari = adjusted_rand_score(y, cluster_labels)

# Compute the normalized mutual information to quantify structural dependence
nmi = normalized_mutual_info_score(y, cluster_labels)

# Print a formatted audit report displaying the external validation metrics
print("=" * 65)
print("AGREEMENT BETWEEN UNSUPERVISED CLUSTERS AND TARGET")
print("=" * 65)
print(f"Adjusted Rand Index (ARI):            {ari:.3f}")
print(f"Normalized Mutual Information (NMI): {nmi:.3f}")
print("=" * 65)

"""### 7.2 Hierarchical view with Ward linkage

To examine the nested grouping structure of the patient observations and provide an alternative perspective to partitioning algorithms, we construct a hierarchical agglomerative clustering tree.

Our pipeline implements:
1. **Ward Linkage Matrix Computation:** Applying Ward's minimum variance method (`linkage` with `method='ward'`) directly on the standardized continuous feature space to minimize total within-cluster variance at each merging step.
2. **Dynamic Threshold Calculation:** Programmatically computing a visualization cut-off height positioned as the midpoint between the merge distances corresponding to the target number of clusters ($K$).
3. **Truncated Dendrogram Generation:** Rendering a compact hierarchical tree (`dendrogram` with `truncate_mode='lastp'`) that summarizes the final clusters while highlighting leaf sample counts in parentheses.
4. **Custom Color Thresholding & Reference Lines:** Coloring branches below the computed threshold to match distinct structural partitions and overlaying a dashed horizontal reference line to visualize the hierarchical cut corresponding to $K = \text{best\_k}$.

### Interpretation

The horizontal cut does not independently demonstrate that K=2 is the optimal number of clusters. Its position is deliberately calculated to visualize the hierarchical structure corresponding to the value of K selected previously through the cluster-number analysis.

The dendrogram therefore provides an alternative hierarchical view of the same data rather than an independent validation of K=2.
"""

# Perform hierarchical clustering using Ward's minimum variance method
Z = linkage(X_scaled, method='ward')

# Choose a threshold between the merge that yields best_k clusters and the next merge.
# For best_k=2 this is the midpoint between the last two merge heights.
if best_k >= 2:
    lower = Z[-best_k, 2]
    upper = Z[-best_k + 1, 2]
    cut_height = (lower + upper) / 2
else:
    cut_height = Z[-1, 2]

# Initialize the figure size for the dendrogram visualization
plt.figure(figsize=(11, 5.5))

# Generate the dendrogram truncating at the last 18 merges to maintain visual clarity
dendrogram(
    Z, truncate_mode='lastp', p=18,
    show_leaf_counts=True, leaf_rotation=0, leaf_font_size=9,
    color_threshold=cut_height, above_threshold_color='#555555'
)

# Draw a dashed reference line representing the cut-off for the chosen K
plt.axhline(cut_height, color='#d95f02', linestyle='--', linewidth=1.8,
            label=f'Visualization cut for K={best_k} (distance={cut_height:.1f})')

# Set bold title and axis labels to ensure academic presentation standards
.title('Hierarchical Dendrogram — Ward Linkage', fontweight='bold')
plt.xlabel('Patient groups (sample count in parentheses)')
plt.ylabel('Ward linkage distance')
plt.legend()

# Remove top and right spines, optimize layout, and render the plot
sns.despine()
plt.tight_layout()
plt.show()

"""### 7.3 Explaining the unsupervised clusters

A Random Forest is trained **only to explain/predict the K-Means cluster labels**. Its feature importance is therefore not the same thing as the importance of the later disease/target classifier.

The two-panel visualization combines complementary levels of interpretation:

1. **Feature Importance:** the Random Forest ranks the continuous variables according to their contribution to distinguishing the K-Means cluster labels.
2. **Standardized Feature Profiles:** horizontal boxplots compare the Z-score distributions of the same variables between Cluster A and Cluster B.

Together, these tools effectively decode the multivariate biological profiles of the unsupervised groupings. Most importantly, they maintain strict methodological rigor by characterizing the dataset's natural variance without illegitimately converting Cluster A and Cluster B into definitive clinical diagnostic categories
"""

# Fit a random forest classifier to predict cluster labels from features
rf_cluster = RandomForestClassifier(
    n_estimators=500, random_state=RANDOM_STATE,
    class_weight='balanced', n_jobs=-1
)
rf_cluster.fit(X_cont, cluster_labels)

# Extract and sort feature importance based on mean impurity decrease
cluster_importance = pd.DataFrame({
    'Feature': continuous_columns,
    'Importance': rf_cluster.feature_importances_
}).sort_values('Importance', ascending=True)

# Prepare standardized data dataframe and melt it for distribution plotting
z_for_plot = pd.DataFrame(X_scaled, columns=continuous_columns)
z_for_plot['Cluster'] = cluster_names.values
long_cluster = z_for_plot.melt(
    id_vars='Cluster', var_name='Feature', value_name='Z-score'
)

# Initialize dual-panel figure for feature importance and cluster profiles
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5.2), gridspec_kw={'width_ratios':[1, 1.6]})

# Configure left panel: horizontal bar chart of cluster-label feature importance
ax1.barh(cluster_importance['Feature'], cluster_importance['Importance'], color='#6baed6')
ax1.set_title('Cluster-Label Feature Importance', fontweight='bold')
ax1.set_xlabel('Mean decrease in Gini impurity')
ax1.grid(axis='x', linestyle=':', alpha=0.35)

# Configure right panel: horizontal boxplots showing z-score profiles per cluster
sns.boxplot(
    data=long_cluster, y='Feature', x='Z-score', hue='Cluster',
    palette=cluster_palette, orient='h', fliersize=2.5, ax=ax2
)
ax2.axvline(0, color='gray', linestyle='--', linewidth=1)
ax2.set_title('Standardized Feature Profiles by Cluster', fontweight='bold')
ax2.set_ylabel('')
ax2.grid(axis='x', linestyle=':', alpha=0.35)

plt.suptitle('Explaining K-Means Clusters', fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Display the sorted feature importance table rounded to 4 decimal places
display(cluster_importance.sort_values('Importance', ascending=False).reset_index(drop=True).round(4))

"""## Phase 8 — Advanced Biomarker Stratification

To examine both the estimated distribution density and summary statistics of key clinical parameters across target classes, we utilize multi-panel violin plots for selected predictive biomarkers (`age`, `thalach`, and `oldpeak`).

Our pipeline implements:
1. **Multi-Panel Biomarker Targeting:** Isolating top continuous features to study their localized expression profiles and distributional shapes relative to clinical outcomes.
2. **Kernel Density Estimation:** Displaying smoothed data distributions (violins) to reveal multimodality, skewness, and probability density across groups.
3. **Internal Boxplot Integration:** Embedding inner box summaries (`inner='box'`) within each violin to simultaneously visualize medians, interquartile ranges, and overall spread.
4. **Custom Palette & Formatting:** Applying a consistent, colorblind-safe palette alongside gridlines to ensure professional and readable visual reporting.
"""

# Define target biomarkers and their corresponding descriptive labels
biomarkers = ['age', 'thalach', 'oldpeak']

biomarker_labels = {
    'age': 'Age (years)',
    'thalach': 'Maximum heart rate (bpm)',
    'oldpeak': 'ST depression (oldpeak)'
}

# Initialize multi-panel figure with 1 row and 3 columns of subplots
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# Define custom color palette for target classes (0 and 1)
violin_palette = {
    0: '#2b83ba',
    1: '#d95f02'
}

# Iterate over axes and biomarkers to plot distribution violins
for ax, col in zip(axes, biomarkers):
    sns.violinplot(
        data=df,
        x='target',
        y=col,
        hue='target',
        palette=violin_palette,
        inner='box',
        cut=0,
        legend=False,
        ax=ax
    )

    # Configure subplot titles, labels, and gridlines
    ax.set_title(
        f'Distribution of {col} by Target Class',
        fontweight='bold'
    )
    ax.set_xlabel('Target class (0 / 1)')
    ax.set_ylabel(biomarker_labels[col])
    ax.grid(axis='y', linestyle=':', alpha=0.35)

# Configure main figure title, adjust layout, and render plot
plt.suptitle(
    'Advanced Biomarker Stratification across Target Classes',
    fontsize=14,
    fontweight='bold',
    y=1.02
)

plt.tight_layout()
plt.show()

"""## Phase 9 — Multi-View Latent Representation & Intermediate Fusion

To integrate heterogeneous clinical dimensions without treating all variables as a single monolithic block, we implement a multi-view framework. The feature space is divided into distinct semantic subsets—specifically a **Clinical/Demographic view** (`age`, `trestbps`, `chol`) and a **Diagnostic/Stress view** (`thalach`, `oldpeak`).

Our pipeline implements:
1. **View-Specific Normalization:** Standardizing each feature subset independently to maintain optimal feature scales within individual domains.
2. **View-Specific Latent Projection:** Applying single-component Principal Component Analysis ($\text{PC1}$) separately to each scaled view, compressing multi-variable medical domains into compact, one-dimensional latent representations.
3. **Cross-View Latent Integration:** Constructing a combined coordinate space mapping the Clinical latent axis against the Diagnostic latent axis.
4. **Bivariate Covariance Ellipses:** Overlaying 95% confidence covariance ellipses for each target class to evaluate how the intermediate fusion of distinct views separates patient groups.
"""

# Defining semantic feature subsets
clinical_features = ['age', 'trestbps', 'chol']
diagnostic_features = ['thalach', 'oldpeak']

# View-Specific Standardization
scaler_clin = StandardScaler()
scaler_diag = StandardScaler()
X_clin_scaled = scaler_clin.fit_transform(df[clinical_features])
X_diag_scaled = scaler_diag.fit_transform(df[diagnostic_features])

# View-Specific latent reduction
clinical_pc1 = PCA(n_components=1).fit_transform(X_clin_scaled).ravel()
diagnostic_pc1 = PCA(n_components=1).fit_transform(X_diag_scaled).ravel()

# Assembling the joint latent space dataframe
latent_view = pd.DataFrame({
    'Clinical_PC1': clinical_pc1,
    'Diagnostic_PC1': diagnostic_pc1,
    'Target': y.map({0:'Class 0', 1:'Class 1'})
})

# Plotting the intermediate fusione space & covarianLOTTING THE INTERMEDIATE FUSION SPACE & COVARIANCE ELLIPSES
fig, ax = plt.subplots(figsize=(8, 6))
sns.scatterplot(
    data=latent_view, x='Clinical_PC1', y='Diagnostic_PC1', hue='Target',
    palette=palette_target, alpha=0.60, s=50, edgecolor='none', ax=ax
)

# Overlaying view-specific 95% confidence ellipses for each target class
for label, color in palette_target.items():
    sub = latent_view[latent_view['Target'] == label]
    add_covariance_ellipse(sub['Clinical_PC1'], sub['Diagnostic_PC1'], ax, color, confidence=0.95)

ax.set_title('Intermediate Multi-View Latent Representation', fontweight='bold')
ax.set_xlabel('Clinical/Demographic View — PC1')
ax.set_ylabel('Diagnostic/Stress View — PC1')
ax.legend(title='Target class')
plt.tight_layout()
plt.show()

"""### 9.1 Patient-distance heatmaps with correct hierarchical linkage

To visually assess the internal cohesion of the cohort, these heatmaps project the symmetric matrix of pairwise Euclidean distances between patients.

From a strictly methodological standpoint, the hierarchical reordering (Ward linkage) is computed exclusively on the original standardized feature vectors. By passing this native linkage explicitly to the visualization, we successfully prevent the geometric distortion that occurs when algorithms incorrectly cluster the distance-matrix rows as if they were newly derived features.

Consequently, these visualizations serve as rigorously ordered clustered patient-distance heatmaps. They effectively expose latent macro-blocks of clinical similarity along the main diagonal, but must be mathematically distinguished from graph-theoretical Patient Similarity Networks (PSNs), maintaining absolute transparency regarding our topological boundaries.
"""

# Define a function to generate a clustered heatmap of patient pairwise distances
def patient_distance_clustermap(dataframe, target, title):
    Xv = StandardScaler().fit_transform(dataframe)
    D = pairwise_distances(Xv, metric='euclidean')
    D_df = pd.DataFrame(D, index=dataframe.index, columns=dataframe.index)

    # Compute ward linkage strictly on the original standardized patient vectors to avoid geometric distortion
    Z_view = linkage(Xv, method='ward')

    # Map the actual clinical target classes to specific colors for visual validation on the heatmap axes
    class_colors = target.map({0:'#2b83ba', 1:'#d95f02'})

    # Generate the clustered heatmap explicitly passing the custom linkage and color
    grid = sns.clustermap(
        D_df,
        row_linkage=Z_view,
        col_linkage=Z_view,
        cmap='Blues',
        row_colors=class_colors,
        col_colors=class_colors,
        xticklabels=False,
        yticklabels=False,
        figsize=(9, 9),
        cbar_kws={'label':'Euclidean distance'}
    )

    # Set a bold title and adjust its vertical position to prevent overlap
    grid.fig.suptitle(title, fontsize=13, fontweight='bold', y=1.02)

    # Label the x and y axes to clarify that each row and column represents an individual patient
    grid.ax_heatmap.set_xlabel('Patients')
    grid.ax_heatmap.set_ylabel('Patients')
    plt.show()

# Apply the function to the clinical and demographic view
patient_distance_clustermap(
    df[clinical_features], y,
    'Patient Distance Heatmap — Clinical/Demographic View'
)

patient_distance_clustermap(
    df[diagnostic_features], y,
    'Patient Distance Heatmap — Diagnostic/Stress View'
)

"""## Phase 10 — True supervised late fusion

Unlike early fusion techniques that indiscriminately concatenate raw data, a rigorously defined late-fusion architecture integrates information at the decision level by combining independent model probabilities rather than raw features or latent coordinates.

Our evaluation pipeline implements a strict multi-model framework:
Stratified Isolation: The patient cohort is partitioned once into training and independent test sets, preserving the exact target class distribution.
View-Specific Modeling: Two independent Random Forest classifiers are trained: one exclusively on the Clinical/Demographic view and another on the Diagnostic/Stress-Test view.
Probabilistic Integration (Late Fusion): The individual predicted probabilities from the two separate views are geometrically averaged to generate a unified, final diagnostic prediction.
Comparative Benchmarking: The late-fusion ensemble is systematically evaluated against the Clinical-only model, the Diagnostic-only model, and a standard flat 5-feature baseline.
Methodological Rigor: By subjecting all individual and fused models to the exact same hold-out patient subset, we guarantee absolute comparative consistency and prevent any potential data leakage across the evaluation metrics.
"""

# Perform stratified train-test data splitting based on target labels
indices = np.arange(len(df))
train_idx, test_idx = train_test_split(
    indices, test_size=0.20, stratify=y, random_state=RANDOM_STATE
)
y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]

# Define a helper function to train random forest and extract probabilities
def fit_rf_view(features):
    model = RandomForestClassifier(
        n_estimators=500,
        random_state=RANDOM_STATE,
        class_weight='balanced',
        n_jobs=-1
    )
    model.fit(df.iloc[train_idx][features], y_train)
    prob = model.predict_proba(df.iloc[test_idx][features])[:, 1]
    return model, prob

# Train view-specific and flat models to obtain out-of-fold probabilities
rf_clinical, prob_clinical = fit_rf_view(clinical_features)
rf_diagnostic, prob_diagnostic = fit_rf_view(diagnostic_features)
rf_flat, prob_flat = fit_rf_view(continuous_columns)

# Equal-weight late fusion of model outputs
prob_fusion = 0.5 * prob_clinical + 0.5 * prob_diagnostic
pred_fusion = (prob_fusion >= 0.5).astype(int)

# Evaluate and store performance metrics (accuracy and roc-auc) for all models
results = []
for name, prob in [
    ('Clinical view', prob_clinical),
    ('Diagnostic view', prob_diagnostic),
    ('Late fusion', prob_fusion),
    ('Flat 5-feature RF', prob_flat),
]:
    pred = (prob >= 0.5).astype(int)
    results.append({
        'Model': name,
        'Accuracy': accuracy_score(y_test, pred),
        'ROC_AUC': roc_auc_score(y_test, prob)
    })

# Compile performance dataframe, sort by roc-auc, and display results
performance_df = pd.DataFrame(results).sort_values('ROC_AUC', ascending=False)
display(performance_df.round(3))
print(); print('Late-fusion classification report:')
print(classification_report(y_test, pred_fusion, digits=3))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Compute and plot confusion matrix for the late fusion model
cm_fusion = confusion_matrix(y_test, pred_fusion)
sns.heatmap(
    cm_fusion, annot=True, fmt='d', cmap='Blues', cbar=False,
    xticklabels=['Pred 0','Pred 1'], yticklabels=['True 0','True 1'], ax=ax1
)
ax1.set_title('Late Fusion — Confusion Matrix', fontweight='bold')
ax1.set_xlabel('Predicted class')
ax1.set_ylabel('True class')

# Iterate through models to compute and plot ROC curves and AUC scores
for name, prob, color in [
    ('Clinical view', prob_clinical, '#7f8c8d'),
    ('Diagnostic view', prob_diagnostic, '#2b83ba'),
    ('Late fusion', prob_fusion, '#d95f02'),
    ('Flat 5-feature RF', prob_flat, '#756bb1')
]:
    fpr, tpr, _ = roc_curve(y_test, prob)
    auc_value = roc_auc_score(y_test, prob)
    ax2.plot(fpr, tpr, linewidth=2, label=f'{name} (AUC={auc_value:.2f})', color=color)

# Configure ROC comparison plot layout, diagonal reference line, and legend
ax2.plot([0,1], [0,1], linestyle='--', color='gray', linewidth=1.2)
ax2.set_xlabel('False Positive Rate')
ax2.set_ylabel('True Positive Rate')
ax2.set_title('ROC Comparison — View-Specific vs Late Fusion', fontweight='bold')
ax2.legend(fontsize=9)
ax2.grid(linestyle=':', alpha=0.35)

plt.tight_layout()
plt.show()

"""## Phase 11 — Explainability of the flat supervised Random Forest baseline

This plot is deliberately labeled as a **flat all-features baseline**. It is separate from the earlier Random Forest used to explain K-Means clusters, so their feature-importance tables cannot be accidentally reused.
"""

# Extract feature importance values from the trained flat random forest model and sort them
flat_importance = pd.DataFrame({
    'Feature': continuous_columns,
    'Importance': rf_flat.feature_importances_
}).sort_values('Importance', ascending=True)

# Plot horizontal bar chart showing global feature importances based on Gini impurity
plt.figure(figsize=(8, 5))
plt.barh(flat_importance['Feature'], flat_importance['Importance'], color='#2b83ba')
plt.xlabel('Mean decrease in Gini impurity')
plt.ylabel('Continuous feature')
plt.title('Flat RF Baseline — Global Feature Importance', fontweight='bold')
plt.grid(axis='x', linestyle=':', alpha=0.35)
plt.tight_layout()
plt.show()

# Display sorted feature importance table rounded to four decimal places
display(flat_importance.sort_values('Importance', ascending=False).reset_index(drop=True).round(4))

"""## Phase 12 — Logistic regression: odds ratios with real 95% confidence intervals

The five continuous predictors are standardized first, so each odds ratio corresponds to a **1-standard-deviation increase** in that feature. `statsmodels.Logit` is used because it provides coefficient standard errors and confidence intervals.

The forest plot describes association with **target Class 1**. It should only be translated into “disease risk” after verifying the target coding from the original dataset documentation.

### Interpretation

- **OR > 1:** a one-standard-deviation increase in the feature is associated with higher odds of Target Class 1, conditional on the other variables in the model.
- **OR < 1:** a one-standard-deviation increase in the feature is associated with lower odds of Target Class 1.
- **OR = 1:** represents the null association.
- If the **95% confidence interval crosses OR = 1**, the estimated association is not statistically distinguishable from the null effect at the conventional 5% significance level.
"""

# Standardize continuous features and add a constant column for the logistic regression intercept
X_logit_z = pd.DataFrame(
    StandardScaler().fit_transform(df[continuous_columns]),
    columns=continuous_columns,
    index=df.index
)
X_logit_sm = sm.add_constant(X_logit_z)

# Fit the logistic regression model using statsmodels
logit_model = sm.Logit(y, X_logit_sm).fit(disp=False, maxiter=1000)

# Extract model parameters, confidence intervals, and p-values while dropping the constant
params = logit_model.params.drop('const')
conf = logit_model.conf_int().drop(index='const')
pvals = logit_model.pvalues.drop('const')

# Compile odds ratios (OR) and confidence intervals into a dataframe and sort by OR
forest_df = pd.DataFrame({
    'Feature': params.index,
    'OR': np.exp(params.values),
    'CI_low': np.exp(conf[0].values),
    'CI_high': np.exp(conf[1].values),
    'p_value': pvals.values
}).sort_values('OR').reset_index(drop=True)

# Prepare positioning and error bar boundaries for the forest plot
pos = np.arange(len(forest_df))
xerr = np.vstack([
    forest_df['OR'] - forest_df['CI_low'],
    forest_df['CI_high'] - forest_df['OR']
])

# Initialize and configure the forest plot figure with error bars and a logarithmic scale
fig, ax = plt.subplots(figsize=(8, 5.5))
ax.errorbar(
    forest_df['OR'], pos, xerr=xerr,
    fmt='o', color='#2b83ba', ecolor='#555555',
    capsize=4, linewidth=1.5, markersize=6
)
ax.axvline(1, color='#d95f02', linestyle='--', linewidth=1.5)
ax.set_xscale('log')
ax.set_yticks(pos)
ax.set_yticklabels(forest_df['Feature'])
ax.set_xlabel('Adjusted Odds Ratio for target Class 1 (95% CI), per 1 SD increase')
ax.set_title('Logistic Regression — Adjusted Odds Ratios', fontweight='bold')
ax.grid(axis='x', linestyle=':', alpha=0.35)
plt.tight_layout()
plt.show()

# Display the final summary dataframe rounded to three decimal places
display(forest_df.round(3))

"""## Phase 13 — Evidence-based conclusions generated from the current run

Use the printed values below to update the presentation instead of keeping numbers copied from an older execution.
"""

# Print a formatted header and separator for the current run execution summary
print('=' * 72)
print('CURRENT-RUN SUMMARY')
print('=' * 72)

# Print total clean observations and class distribution counts from the dataset
print(f'Clean observations: {len(df)}')
print(f'Class counts: {y.value_counts().sort_index().to_dict()}')

# Print principal component variance percentages and cumulative thresholds
print(f'PC1 variance: {var_pc1:.2f}%')
print(f'PC2 variance: {var_pc2:.2f}%')
print(f'PC1 + PC2: {var_pc1 + var_pc2:.2f}%')
print(f'Components to exceed 80% variance: {n80}')

# Print unsupervised clustering evaluation metrics including silhouette score, ARI, and NMI
print(f'Best K by silhouette: {best_k} (silhouette={best_silhouette:.3f})')
print(f'ARI vs target: {ari:.3f}')
print(f'NMI vs target: {nmi:.3f}')

# Print supervised model comparison performance dataframe and closing separator
print(); print('Supervised model comparison:')
print(performance_df.round(3).to_string(index=False))
print('=' * 72)